//
// Milkyway Hierarchical Verilog Dump:
// Generated on 08/02/2018 at 07:54:12
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :i2c_master_top
// Cell Name    :i2c_master_top
// Hierarchy delimiter:'/'
// Write Command : write_verilog ./output/i2c_master_top_icc_nopg.v -no_physical_only_cells
//


module i2c_master_bit_ctrl_DW01_dec_1 (SUM , A );
output [15:0] SUM ;
input  [15:0] A ;



INV_X1 U1 (.A ( n34 ) , .ZN ( n3 ) ) ;
INV_X1 U9 (.A ( n26 ) , .ZN ( SUM[7] ) ) ;
INV_X1 U8 (.A ( n22 ) , .ZN ( SUM[9] ) ) ;
INV_X1 U7 (.A ( n36 ) , .ZN ( SUM[11] ) ) ;
INV_X1 U6 (.A ( n31 ) , .ZN ( n10 ) ) ;
INV_X1 U5 (.A ( n30 ) , .ZN ( n9 ) ) ;
INV_X1 U4 (.A ( n27 ) , .ZN ( n6 ) ) ;
INV_X1 U3 (.A ( n28 ) , .ZN ( n7 ) ) ;
INV_X1 U2 (.A ( n29 ) , .ZN ( n8 ) ) ;
INV_X1 U17 (.A ( A[12] ) , .ZN ( n20 ) ) ;
INV_X1 U16 (.A ( A[0] ) , .ZN ( SUM[0] ) ) ;
OR2_X1 U15 (.A1 ( n6 ) , .A2 ( A[6] ) , .ZN ( n1 ) ) ;
INV_X1 U14 (.A ( A[2] ) , .ZN ( n13 ) ) ;
INV_X1 U13 (.A ( A[3] ) , .ZN ( n14 ) ) ;
INV_X1 U12 (.A ( A[4] ) , .ZN ( n15 ) ) ;
INV_X1 U11 (.A ( A[5] ) , .ZN ( n16 ) ) ;
INV_X1 U10 (.A ( A[6] ) , .ZN ( n17 ) ) ;
OAI21_X1 U25 (.A ( n1 ) , .B1 ( n27 ) , .B2 ( n17 ) , .ZN ( SUM[6] ) ) ;
AOI21_X1 U24 (.A ( n25 ) , .B1 ( n1 ) , .B2 ( A[7] ) , .ZN ( n26 ) ) ;
OAI21_X1 U23 (.A ( n23 ) , .B1 ( n25 ) , .B2 ( n18 ) , .ZN ( SUM[8] ) ) ;
AOI21_X1 U22 (.A ( n24 ) , .B1 ( n23 ) , .B2 ( A[9] ) , .ZN ( n22 ) ) ;
INV_X1 U21 (.A ( A[1] ) , .ZN ( n12 ) ) ;
INV_X1 U20 (.A ( A[13] ) , .ZN ( n21 ) ) ;
INV_X1 U19 (.A ( A[8] ) , .ZN ( n18 ) ) ;
INV_X1 U18 (.A ( A[10] ) , .ZN ( n19 ) ) ;
XNOR2_X1 U33 (.A ( A[14] ) , .B ( n33 ) , .ZN ( SUM[14] ) ) ;
NOR2_X1 U32 (.A1 ( A[14] ) , .A2 ( n33 ) , .ZN ( n32 ) ) ;
XOR2_X1 U31 (.A ( A[15] ) , .B ( n32 ) , .Z ( SUM[15] ) ) ;
OAI21_X1 U30 (.A ( n10 ) , .B1 ( SUM[0] ) , .B2 ( n12 ) , .ZN ( SUM[1] ) ) ;
OAI21_X1 U29 (.A ( n9 ) , .B1 ( n31 ) , .B2 ( n13 ) , .ZN ( SUM[2] ) ) ;
OAI21_X1 U28 (.A ( n8 ) , .B1 ( n30 ) , .B2 ( n14 ) , .ZN ( SUM[3] ) ) ;
OAI21_X1 U27 (.A ( n7 ) , .B1 ( n29 ) , .B2 ( n15 ) , .ZN ( SUM[4] ) ) ;
OAI21_X1 U26 (.A ( n6 ) , .B1 ( n28 ) , .B2 ( n16 ) , .ZN ( SUM[5] ) ) ;
NAND2_X1 U41 (.A1 ( n24 ) , .A2 ( n19 ) , .ZN ( n37 ) ) ;
OAI21_X1 U40 (.A ( n37 ) , .B1 ( n24 ) , .B2 ( n19 ) , .ZN ( SUM[10] ) ) ;
NOR2_X1 U39 (.A1 ( n37 ) , .A2 ( A[11] ) , .ZN ( n35 ) ) ;
AOI21_X1 U38 (.A ( n35 ) , .B1 ( n37 ) , .B2 ( A[11] ) , .ZN ( n36 ) ) ;
NAND2_X1 U37 (.A1 ( n35 ) , .A2 ( n20 ) , .ZN ( n34 ) ) ;
OAI21_X1 U36 (.A ( n34 ) , .B1 ( n35 ) , .B2 ( n20 ) , .ZN ( SUM[12] ) ) ;
NAND2_X1 U35 (.A1 ( n3 ) , .A2 ( n21 ) , .ZN ( n33 ) ) ;
OAI21_X1 U34 (.A ( n33 ) , .B1 ( n3 ) , .B2 ( n21 ) , .ZN ( SUM[13] ) ) ;
NOR2_X1 U49 (.A1 ( A[1] ) , .A2 ( A[0] ) , .ZN ( n31 ) ) ;
NOR2_X1 U48 (.A1 ( n10 ) , .A2 ( A[2] ) , .ZN ( n30 ) ) ;
NOR2_X1 U47 (.A1 ( n9 ) , .A2 ( A[3] ) , .ZN ( n29 ) ) ;
NOR2_X1 U46 (.A1 ( n8 ) , .A2 ( A[4] ) , .ZN ( n28 ) ) ;
NOR2_X1 U45 (.A1 ( n7 ) , .A2 ( A[5] ) , .ZN ( n27 ) ) ;
NOR2_X1 U44 (.A1 ( n1 ) , .A2 ( A[7] ) , .ZN ( n25 ) ) ;
NAND2_X1 U43 (.A1 ( n25 ) , .A2 ( n18 ) , .ZN ( n23 ) ) ;
NOR2_X1 U42 (.A1 ( n23 ) , .A2 ( A[9] ) , .ZN ( n24 ) ) ;
endmodule




module i2c_master_bit_ctrl_DW01_dec_0 (SUM , A );
output [13:0] SUM ;
input  [13:0] A ;



INV_X1 U3 (.A ( n27 ) , .ZN ( n8 ) ) ;
INV_X1 U2 (.A ( n28 ) , .ZN ( n9 ) ) ;
INV_X1 U1 (.A ( n31 ) , .ZN ( n3 ) ) ;
INV_X1 U11 (.A ( A[5] ) , .ZN ( n16 ) ) ;
INV_X1 U10 (.A ( A[6] ) , .ZN ( n17 ) ) ;
INV_X1 U9 (.A ( n24 ) , .ZN ( SUM[7] ) ) ;
INV_X1 U8 (.A ( n20 ) , .ZN ( SUM[9] ) ) ;
INV_X1 U7 (.A ( n32 ) , .ZN ( SUM[11] ) ) ;
INV_X1 U6 (.A ( n29 ) , .ZN ( n10 ) ) ;
INV_X1 U5 (.A ( n25 ) , .ZN ( n6 ) ) ;
INV_X1 U4 (.A ( n26 ) , .ZN ( n7 ) ) ;
INV_X1 U19 (.A ( A[10] ) , .ZN ( n19 ) ) ;
INV_X1 U18 (.A ( A[8] ) , .ZN ( n18 ) ) ;
OR2_X1 U17 (.A1 ( n6 ) , .A2 ( A[6] ) , .ZN ( n1 ) ) ;
INV_X1 U16 (.A ( A[0] ) , .ZN ( SUM[0] ) ) ;
INV_X1 U15 (.A ( A[1] ) , .ZN ( n12 ) ) ;
INV_X1 U14 (.A ( A[2] ) , .ZN ( n13 ) ) ;
INV_X1 U13 (.A ( A[3] ) , .ZN ( n14 ) ) ;
INV_X1 U12 (.A ( A[4] ) , .ZN ( n15 ) ) ;
OAI21_X1 U27 (.A ( n9 ) , .B1 ( n29 ) , .B2 ( n13 ) , .ZN ( SUM[2] ) ) ;
OAI21_X1 U26 (.A ( n8 ) , .B1 ( n28 ) , .B2 ( n14 ) , .ZN ( SUM[3] ) ) ;
OAI21_X1 U25 (.A ( n7 ) , .B1 ( n27 ) , .B2 ( n15 ) , .ZN ( SUM[4] ) ) ;
OAI21_X1 U24 (.A ( n6 ) , .B1 ( n26 ) , .B2 ( n16 ) , .ZN ( SUM[5] ) ) ;
OAI21_X1 U23 (.A ( n1 ) , .B1 ( n25 ) , .B2 ( n17 ) , .ZN ( SUM[6] ) ) ;
AOI21_X1 U22 (.A ( n23 ) , .B1 ( n1 ) , .B2 ( A[7] ) , .ZN ( n24 ) ) ;
OAI21_X1 U21 (.A ( n21 ) , .B1 ( n23 ) , .B2 ( n18 ) , .ZN ( SUM[8] ) ) ;
AOI21_X1 U20 (.A ( n22 ) , .B1 ( n21 ) , .B2 ( A[9] ) , .ZN ( n20 ) ) ;
NAND2_X1 U35 (.A1 ( n22 ) , .A2 ( n19 ) , .ZN ( n33 ) ) ;
OAI21_X1 U34 (.A ( n33 ) , .B1 ( n22 ) , .B2 ( n19 ) , .ZN ( SUM[10] ) ) ;
NOR2_X1 U33 (.A1 ( n33 ) , .A2 ( A[11] ) , .ZN ( n31 ) ) ;
AOI21_X1 U32 (.A ( n31 ) , .B1 ( n33 ) , .B2 ( A[11] ) , .ZN ( n32 ) ) ;
XNOR2_X1 U31 (.A ( A[12] ) , .B ( n3 ) , .ZN ( SUM[12] ) ) ;
NOR2_X1 U30 (.A1 ( A[12] ) , .A2 ( n3 ) , .ZN ( n30 ) ) ;
XOR2_X1 U29 (.A ( A[13] ) , .B ( n30 ) , .Z ( SUM[13] ) ) ;
OAI21_X1 U28 (.A ( n10 ) , .B1 ( SUM[0] ) , .B2 ( n12 ) , .ZN ( SUM[1] ) ) ;
NOR2_X1 U43 (.A1 ( A[1] ) , .A2 ( A[0] ) , .ZN ( n29 ) ) ;
NOR2_X1 U42 (.A1 ( n10 ) , .A2 ( A[2] ) , .ZN ( n28 ) ) ;
NOR2_X1 U41 (.A1 ( n9 ) , .A2 ( A[3] ) , .ZN ( n27 ) ) ;
NOR2_X1 U40 (.A1 ( n8 ) , .A2 ( A[4] ) , .ZN ( n26 ) ) ;
NOR2_X1 U39 (.A1 ( n7 ) , .A2 ( A[5] ) , .ZN ( n25 ) ) ;
NOR2_X1 U38 (.A1 ( n1 ) , .A2 ( A[7] ) , .ZN ( n23 ) ) ;
NAND2_X1 U37 (.A1 ( n23 ) , .A2 ( n18 ) , .ZN ( n21 ) ) ;
NOR2_X1 U36 (.A1 ( n21 ) , .A2 ( A[9] ) , .ZN ( n22 ) ) ;
endmodule




module i2c_master_bit_ctrl (scl_oen , sda_o , sda_oen , clk_cts_0 , 
    clk_cts_1 , clk_cts_2 , din , scl_i , sda_i , cmd_ack , busy , al , 
    dout , scl_o , cmd , clk , rst , nReset , ena , clk_cnt , 
    clk_cts_3 , clk_cts_4 , clk_cts_5 , clk_cts_6 , clk_cts_8 , 
    clk_cts_9 , clk_cts_0_1 , clk_cts_1_1 , clk_cts_2_1 , clk_cts_3_1 , 
    clk_cts_5_1 , clk_cts_6_1 , cts_0 );
output scl_oen ;
output sda_o ;
output sda_oen ;
input  clk_cts_0 ;
input  clk_cts_1 ;
input  clk_cts_2 ;
input  din ;
input  scl_i ;
input  sda_i ;
output cmd_ack ;
output busy ;
output al ;
output dout ;
output scl_o ;
input  [3:0] cmd ;
input  clk ;
input  rst ;
input  nReset ;
input  ena ;
input  [15:0] clk_cnt ;
input  clk_cts_3 ;
input  clk_cts_4 ;
input  clk_cts_5 ;
input  clk_cts_6 ;
input  clk_cts_8 ;
input  clk_cts_9 ;
input  clk_cts_0_1 ;
input  clk_cts_1_1 ;
input  clk_cts_2_1 ;
input  clk_cts_3_1 ;
input  clk_cts_5_1 ;
input  clk_cts_6_1 ;
input  cts_0 ;

wire [15:0] cnt ;
wire [13:0] filter_cnt ;



i2c_master_bit_ctrl_DW01_dec_1 sub_245 (
    .SUM ( {N390 , N380 , N370 , N360 , N350 , N340 , N330 , N320 , N310 , 
	N303 , N290 , N280 , N2710 , N2610 , N2510 , N2410 } ) , 
    .A ( cnt ) ) ;


i2c_master_bit_ctrl_DW01_dec_0 sub_277 (
    .SUM ( {N800 , N790 , N780 , N770 , N760 , N750 , N740 , N730 , N720 , 
	N710 , N700 , N690 , N680 , N670 } ) , 
    .A ( filter_cnt ) ) ;

CLKBUF_X1 U227 (.A ( n12 ) , .Z ( n302 ) ) ;
BUF_X1 U226 (.A ( n302 ) , .Z ( n301 ) ) ;
BUF_X1 U225 (.A ( n181 ) , .Z ( n300 ) ) ;
BUF_X1 U224 (.A ( N19 ) , .Z ( n299 ) ) ;
BUF_X1 U199 (.A ( n10 ) , .Z ( n296 ) ) ;
CLKBUF_X1 U2 (.A ( n216 ) , .Z ( n298 ) ) ;
BUF_X1 U1 (.A ( n217 ) , .Z ( n297 ) ) ;
CLKBUF_X1 CLKBUF_X1_G1B1I23 (.A ( clk_cts_5_1 ) , .Z ( wb_clk_i_G1B2I23 ) ) ;
CLKBUF_X1 CLKBUF_X1_G1B1I13_1 (.A ( clk_cts_6_1 ) , .Z ( wb_clk_i_G1B2I13 ) ) ;
CLKBUF_X2 CLKBUF_X1_G1B1I16_1 (.A ( clk_cts_5_1 ) , .Z ( wb_clk_i_G1B2I16 ) ) ;
CLKBUF_X1 CLKBUF_X1_G1B1I22 (.A ( cts_0 ) , .Z ( wb_clk_i_G1B2I22 ) ) ;
CLKBUF_X1 CLKBUF_X1_G1B1I2 (.A ( cts_0 ) , .Z ( wb_clk_i_G1B2I2 ) ) ;
NAND4_X1 U223 (.A1 ( n104 ) , .A2 ( n221 ) , .A3 ( n223 ) , .A4 ( n96 ) 
    , .ZN ( n590 ) ) ;
NAND2_X1 U129 (.A1 ( N730 ) , .A2 ( n134 ) , .ZN ( n141 ) ) ;
OAI21_X1 U130 (.A ( n142 ) , .B1 ( n158 ) , .B2 ( n132 ) , .ZN ( N86 ) ) ;
NAND2_X1 U131 (.A1 ( N720 ) , .A2 ( n134 ) , .ZN ( n142 ) ) ;
OAI21_X1 U132 (.A ( n143 ) , .B1 ( n159 ) , .B2 ( n132 ) , .ZN ( N85 ) ) ;
NAND2_X1 U133 (.A1 ( N710 ) , .A2 ( n134 ) , .ZN ( n143 ) ) ;
OAI21_X1 U134 (.A ( n144 ) , .B1 ( n161 ) , .B2 ( n132 ) , .ZN ( N84 ) ) ;
NAND2_X1 U135 (.A1 ( N700 ) , .A2 ( n134 ) , .ZN ( n144 ) ) ;
OAI21_X1 U136 (.A ( n145 ) , .B1 ( n170 ) , .B2 ( n132 ) , .ZN ( N83 ) ) ;
NAND2_X1 U137 (.A1 ( N690 ) , .A2 ( n134 ) , .ZN ( n145 ) ) ;
OAI21_X1 U138 (.A ( n146 ) , .B1 ( n172 ) , .B2 ( n132 ) , .ZN ( N820 ) ) ;
NAND2_X1 U139 (.A1 ( N680 ) , .A2 ( n134 ) , .ZN ( n146 ) ) ;
OAI22_X1 U140 (.A1 ( n188 ) , .A2 ( n14 ) , .B1 ( n126 ) , .B2 ( n16 ) 
    , .ZN ( n189 ) ) ;
INV_X1 U141 (.A ( n126 ) , .ZN ( n14 ) ) ;
NAND2_X1 U142 (.A1 ( n186 ) , .A2 ( n187 ) , .ZN ( n126 ) ) ;
NAND3_X1 U143 (.A1 ( n106 ) , .A2 ( n79 ) , .A3 ( n108 ) , .ZN ( n74 ) ) ;
NAND3_X1 U144 (.A1 ( n224 ) , .A2 ( n78 ) , .A3 ( n101 ) , .ZN ( n75 ) ) ;
INV_X1 U145 (.A ( cmd[1] ) , .ZN ( n1180 ) ) ;
AND3_X1 U146 (.A1 ( n112 ) , .A2 ( n45 ) , .A3 ( n236 ) , .ZN ( n102 ) ) ;
AND4_X1 U147 (.A1 ( n221 ) , .A2 ( n222 ) , .A3 ( n171 ) , .A4 ( n223 ) 
    , .ZN ( n112 ) ) ;
NOR2_X1 U148 (.A1 ( n78 ) , .A2 ( n44 ) , .ZN ( n171 ) ) ;
AND4_X1 U149 (.A1 ( n65 ) , .A2 ( n112 ) , .A3 ( n237 ) , .A4 ( n3 ) 
    , .ZN ( n108 ) ) ;
AOI21_X1 U150 (.A ( rst ) , .B1 ( n128 ) , .B2 ( n129 ) , .ZN ( n192 ) ) ;
NAND2_X1 U151 (.A1 ( n193 ) , .A2 ( n24 ) , .ZN ( n128 ) ) ;
OR4_X1 U152 (.A1 ( n1180 ) , .A2 ( n1150 ) , .A3 ( cmd[3] ) , .A4 ( n193 ) 
    , .ZN ( n129 ) ) ;
INV_X1 U153 (.A ( n68 ) , .ZN ( n1150 ) ) ;
AND3_X1 U154 (.A1 ( n231 ) , .A2 ( n95 ) , .A3 ( n230 ) , .ZN ( n3 ) ) ;
AND4_X1 U155 (.A1 ( n209 ) , .A2 ( n208 ) , .A3 ( n207 ) , .A4 ( n206 ) 
    , .ZN ( n167 ) ) ;
AND4_X1 U156 (.A1 ( n205 ) , .A2 ( n204 ) , .A3 ( n203 ) , .A4 ( n202 ) 
    , .ZN ( n166 ) ) ;
INV_X1 U157 (.A ( clk_cnt[15] ) , .ZN ( n125 ) ) ;
INV_X1 U158 (.A ( clk_cnt[14] ) , .ZN ( n127 ) ) ;
INV_X1 U159 (.A ( clk_cnt[13] ) , .ZN ( n130 ) ) ;
INV_X1 U160 (.A ( clk_cnt[12] ) , .ZN ( n131 ) ) ;
INV_X1 U161 (.A ( clk_cnt[11] ) , .ZN ( n153 ) ) ;
INV_X1 U162 (.A ( clk_cnt[10] ) , .ZN ( n155 ) ) ;
INV_X1 U163 (.A ( clk_cnt[9] ) , .ZN ( n156 ) ) ;
INV_X1 U164 (.A ( clk_cnt[8] ) , .ZN ( n157 ) ) ;
AND4_X1 U165 (.A1 ( n201 ) , .A2 ( n200 ) , .A3 ( n199 ) , .A4 ( n198 ) 
    , .ZN ( n165 ) ) ;
INV_X1 U166 (.A ( clk_cnt[7] ) , .ZN ( n158 ) ) ;
INV_X1 U167 (.A ( clk_cnt[6] ) , .ZN ( n159 ) ) ;
INV_X1 U168 (.A ( clk_cnt[5] ) , .ZN ( n161 ) ) ;
INV_X1 U169 (.A ( clk_cnt[4] ) , .ZN ( n170 ) ) ;
INV_X1 U170 (.A ( clk_cnt[3] ) , .ZN ( n172 ) ) ;
INV_X1 U171 (.A ( clk_cnt[2] ) , .ZN ( n173 ) ) ;
AND4_X1 U172 (.A1 ( n124 ) , .A2 ( n186 ) , .A3 ( n185 ) , .A4 ( n220 ) 
    , .ZN ( N1160 ) ) ;
INV_X1 U173 (.A ( n33 ) , .ZN ( n252 ) ) ;
AOI222_X1 U174 (.A1 ( clk_cnt[1] ) , .A2 ( N218 ) , .B1 ( N2510 ) , .B2 ( n5 ) 
    , .C1 ( n32 ) , .C2 ( cnt[1] ) , .ZN ( n33 ) ) ;
INV_X1 U175 (.A ( n35 ) , .ZN ( n253 ) ) ;
AOI222_X1 U176 (.A1 ( clk_cnt[0] ) , .A2 ( N218 ) , .B1 ( N2410 ) , .B2 ( n5 ) 
    , .C1 ( n32 ) , .C2 ( cnt[0] ) , .ZN ( n35 ) ) ;
AND2_X1 U177 (.A1 ( scl_i ) , .A2 ( n124 ) , .ZN ( N59 ) ) ;
AND2_X1 U178 (.A1 ( sda_i ) , .A2 ( n124 ) , .ZN ( N61 ) ) ;
OAI211_X1 U179 (.A ( n296 ) , .B ( n124 ) , .C1 ( n298 ) , .C2 ( n297 ) 
    , .ZN ( N110 ) ) ;
INV_X1 U180 (.A ( n174 ) , .ZN ( n10 ) ) ;
AOI21_X1 U181 (.A ( n215 ) , .B1 ( n217 ) , .B2 ( n216 ) , .ZN ( n174 ) ) ;
OAI211_X1 U182 (.A ( n8 ) , .B ( n124 ) , .C1 ( n213 ) , .C2 ( n214 ) 
    , .ZN ( N109 ) ) ;
INV_X1 U183 (.A ( n176 ) , .ZN ( n8 ) ) ;
AOI21_X1 U184 (.A ( n212 ) , .B1 ( n214 ) , .B2 ( n213 ) , .ZN ( n176 ) ) ;
AND2_X1 U185 (.A1 ( n169 ) , .A2 ( n124 ) , .ZN ( N1230 ) ) ;
NOR2_X1 U186 (.A1 ( rst ) , .A2 ( n300 ) , .ZN ( N60 ) ) ;
NOR2_X1 U187 (.A1 ( rst ) , .A2 ( n182 ) , .ZN ( N620 ) ) ;
INV_X1 U188 (.A ( rst ) , .ZN ( n124 ) ) ;
AND4_X1 U189 (.A1 ( n65 ) , .A2 ( n45 ) , .A3 ( n224 ) , .A4 ( n235 ) 
    , .ZN ( n104 ) ) ;
INV_X1 U190 (.A ( n121 ) , .ZN ( n65 ) ) ;
NAND4_X1 U191 (.A1 ( n234 ) , .A2 ( n237 ) , .A3 ( n3 ) , .A4 ( n106 ) 
    , .ZN ( n120 ) ) ;
NAND2_X1 U192 (.A1 ( n111 ) , .A2 ( n236 ) , .ZN ( n121 ) ) ;
NAND4_X1 U193 (.A1 ( n111 ) , .A2 ( n112 ) , .A3 ( n45 ) , .A4 ( n64 ) 
    , .ZN ( n47 ) ) ;
NOR3_X1 U194 (.A1 ( n98 ) , .A2 ( n107 ) , .A3 ( n1090 ) , .ZN ( n111 ) ) ;
AND4_X1 U195 (.A1 ( n222 ) , .A2 ( n223 ) , .A3 ( n221 ) , .A4 ( n119 ) 
    , .ZN ( n101 ) ) ;
NAND4_X1 U196 (.A1 ( n226 ) , .A2 ( n227 ) , .A3 ( n102 ) , .A4 ( n1090 ) 
    , .ZN ( n49 ) ) ;
NAND4_X1 U197 (.A1 ( n225 ) , .A2 ( n227 ) , .A3 ( n102 ) , .A4 ( n98 ) 
    , .ZN ( n46 ) ) ;
OAI22_X1 U198 (.A1 ( n227 ) , .A2 ( n39 ) , .B1 ( n610 ) , .B2 ( n66 ) 
    , .ZN ( n261 ) ) ;
NAND3_X1 U200 (.A1 ( n930 ) , .A2 ( n100 ) , .A3 ( n95 ) , .ZN ( n920 ) ) ;
NAND4_X1 U201 (.A1 ( n95 ) , .A2 ( n103 ) , .A3 ( n231 ) , .A4 ( n97 ) 
    , .ZN ( n71 ) ) ;
NAND3_X1 U202 (.A1 ( n231 ) , .A2 ( n95 ) , .A3 ( n230 ) , .ZN ( n160 ) ) ;
OAI22_X1 U203 (.A1 ( n225 ) , .A2 ( n39 ) , .B1 ( n610 ) , .B2 ( n46 ) 
    , .ZN ( n259 ) ) ;
NOR3_X1 U204 (.A1 ( n840 ) , .A2 ( n34 ) , .A3 ( n80 ) , .ZN ( n830 ) ) ;
INV_X1 U205 (.A ( n46 ) , .ZN ( n37 ) ) ;
AND4_X1 U206 (.A1 ( n46 ) , .A2 ( n75 ) , .A3 ( n71 ) , .A4 ( n920 ) 
    , .ZN ( n910 ) ) ;
NAND4_X1 U207 (.A1 ( n47 ) , .A2 ( n50 ) , .A3 ( n900 ) , .A4 ( n910 ) 
    , .ZN ( n840 ) ) ;
OAI21_X1 U208 (.A ( n67 ) , .B1 ( n228 ) , .B2 ( n39 ) , .ZN ( n262 ) ) ;
NAND4_X1 U209 (.A1 ( n930 ) , .A2 ( n231 ) , .A3 ( n228 ) , .A4 ( n105 ) 
    , .ZN ( n48 ) ) ;
NOR2_X1 U210 (.A1 ( n120 ) , .A2 ( n121 ) , .ZN ( n119 ) ) ;
INV_X1 U211 (.A ( n120 ) , .ZN ( n45 ) ) ;
OAI21_X4 U212 (.A ( n52 ) , .B1 ( n193 ) , .B2 ( n870 ) , .ZN ( n39 ) ) ;
NOR4_X1 U214 (.A1 ( n880 ) , .A2 ( n890 ) , .A3 ( n36 ) , .A4 ( n840 ) 
    , .ZN ( n870 ) ) ;
OAI22_X1 U215 (.A1 ( n229 ) , .A2 ( n39 ) , .B1 ( n610 ) , .B2 ( n71 ) 
    , .ZN ( n263 ) ) ;
OAI22_X1 U216 (.A1 ( n221 ) , .A2 ( n39 ) , .B1 ( n610 ) , .B2 ( n590 ) 
    , .ZN ( n255 ) ) ;
OAI22_X1 U217 (.A1 ( n39 ) , .A2 ( n1100 ) , .B1 ( n610 ) , .B2 ( n590 ) 
    , .ZN ( n272 ) ) ;
NAND4_X1 U218 (.A1 ( n57 ) , .A2 ( n58 ) , .A3 ( n590 ) , .A4 ( n600 ) 
    , .ZN ( n54 ) ) ;
NAND4_X1 U219 (.A1 ( n930 ) , .A2 ( n231 ) , .A3 ( n229 ) , .A4 ( n850 ) 
    , .ZN ( n66 ) ) ;
AND3_X1 U220 (.A1 ( n58 ) , .A2 ( n74 ) , .A3 ( n590 ) , .ZN ( n900 ) ) ;
NAND4_X1 U221 (.A1 ( n104 ) , .A2 ( n222 ) , .A3 ( n223 ) , .A4 ( n860 ) 
    , .ZN ( n600 ) ) ;
NAND4_X1 U222 (.A1 ( n104 ) , .A2 ( n221 ) , .A3 ( n222 ) , .A4 ( n940 ) 
    , .ZN ( n58 ) ) ;
NAND4_X1 U35 (.A1 ( ena ) , .A2 ( n162 ) , .A3 ( n163 ) , .A4 ( n124 ) 
    , .ZN ( N218 ) ) ;
NAND4_X1 U36 (.A1 ( n164 ) , .A2 ( n165 ) , .A3 ( n166 ) , .A4 ( n167 ) 
    , .ZN ( n163 ) ) ;
OR3_X1 U37 (.A1 ( n187 ) , .A2 ( n186 ) , .A3 ( n20 ) , .ZN ( n162 ) ) ;
AND4_X1 U38 (.A1 ( n197 ) , .A2 ( n196 ) , .A3 ( n195 ) , .A4 ( n194 ) 
    , .ZN ( n164 ) ) ;
NOR3_X1 U40 (.A1 ( n51 ) , .A2 ( cmd[3] ) , .A3 ( n610 ) , .ZN ( n63 ) ) ;
NOR4_X1 U41 (.A1 ( filter_cnt[9] ) , .A2 ( filter_cnt[8] ) 
    , .A3 ( filter_cnt[7] ) , .A4 ( filter_cnt[6] ) , .ZN ( n152 ) ) ;
NAND4_X1 U42 (.A1 ( n65 ) , .A2 ( n112 ) , .A3 ( n234 ) , .A4 ( n106 ) 
    , .ZN ( n99 ) ) ;
NAND4_X1 U43 (.A1 ( n225 ) , .A2 ( n226 ) , .A3 ( n102 ) , .A4 ( n107 ) 
    , .ZN ( n50 ) ) ;
NOR2_X1 U44 (.A1 ( cmd[0] ) , .A2 ( cmd[2] ) , .ZN ( n68 ) ) ;
NAND4_X1 U45 (.A1 ( n108 ) , .A2 ( n234 ) , .A3 ( n233 ) , .A4 ( n55 ) 
    , .ZN ( n72 ) ) ;
NOR4_X1 U46 (.A1 ( rst ) , .A2 ( n185 ) , .A3 ( n220 ) , .A4 ( n301 ) 
    , .ZN ( N115 ) ) ;
NAND2_X1 U47 (.A1 ( n117 ) , .A2 ( n237 ) , .ZN ( n51 ) ) ;
NOR2_X1 U48 (.A1 ( n56 ) , .A2 ( n99 ) , .ZN ( n97 ) ) ;
AOI211_X1 U49 (.A ( sto_condition ) , .B ( rst ) , .C1 ( n178 ) , .C2 ( n177 ) 
    , .ZN ( N118 ) ) ;
NAND4_X1 U50 (.A1 ( n149 ) , .A2 ( n150 ) , .A3 ( n151 ) , .A4 ( n152 ) 
    , .ZN ( n148 ) ) ;
NOR3_X1 U51 (.A1 ( filter_cnt[10] ) , .A2 ( filter_cnt[0] ) 
    , .A3 ( filter_cnt[11] ) , .ZN ( n149 ) ) ;
NOR3_X1 U52 (.A1 ( filter_cnt[4] ) , .A2 ( filter_cnt[3] ) 
    , .A3 ( filter_cnt[5] ) , .ZN ( n151 ) ) ;
NOR4_X1 U53 (.A1 ( filter_cnt[2] ) , .A2 ( filter_cnt[1] ) 
    , .A3 ( filter_cnt[13] ) , .A4 ( filter_cnt[12] ) , .ZN ( n150 ) ) ;
OAI21_X1 U54 (.A ( n135 ) , .B1 ( n127 ) , .B2 ( n132 ) , .ZN ( N93 ) ) ;
NAND2_X1 U55 (.A1 ( N790 ) , .A2 ( n134 ) , .ZN ( n135 ) ) ;
AOI21_X1 U56 (.A ( n186 ) , .B1 ( n22 ) , .B2 ( n168 ) , .ZN ( N19 ) ) ;
NAND2_X1 U57 (.A1 ( n179 ) , .A2 ( scl_oen ) , .ZN ( n168 ) ) ;
NAND4_X1 U58 (.A1 ( n48 ) , .A2 ( n49 ) , .A3 ( n600 ) , .A4 ( n154 ) 
    , .ZN ( n890 ) ) ;
NAND4_X1 U59 (.A1 ( n108 ) , .A2 ( n234 ) , .A3 ( n232 ) , .A4 ( n82 ) 
    , .ZN ( n154 ) ) ;
OAI221_X1 U60 (.A ( n124 ) , .B1 ( n216 ) , .B2 ( n122 ) , .C1 ( n217 ) 
    , .C2 ( n123 ) , .ZN ( n275 ) ) ;
OAI221_X1 U61 (.A ( n124 ) , .B1 ( n213 ) , .B2 ( n122 ) , .C1 ( n214 ) 
    , .C2 ( n123 ) , .ZN ( n278 ) ) ;
OAI221_X1 U62 (.A ( n124 ) , .B1 ( n217 ) , .B2 ( n122 ) , .C1 ( n123 ) 
    , .C2 ( n210 ) , .ZN ( n276 ) ) ;
OAI221_X1 U63 (.A ( n124 ) , .B1 ( n214 ) , .B2 ( n122 ) , .C1 ( n123 ) 
    , .C2 ( n211 ) , .ZN ( n279 ) ) ;
OAI221_X1 U64 (.A ( n4 ) , .B1 ( n194 ) , .B2 ( n1 ) , .C1 ( n2 ) , .C2 ( n125 ) 
    , .ZN ( n238 ) ) ;
NAND2_X1 U65 (.A1 ( N390 ) , .A2 ( n5 ) , .ZN ( n4 ) ) ;
OAI221_X1 U66 (.A ( n7 ) , .B1 ( n195 ) , .B2 ( n1 ) , .C1 ( n2 ) , .C2 ( n127 ) 
    , .ZN ( n239 ) ) ;
NAND2_X1 U67 (.A1 ( N380 ) , .A2 ( n5 ) , .ZN ( n7 ) ) ;
OAI221_X1 U68 (.A ( n9 ) , .B1 ( n196 ) , .B2 ( n1 ) , .C1 ( n2 ) , .C2 ( n130 ) 
    , .ZN ( n240 ) ) ;
NAND2_X1 U69 (.A1 ( N370 ) , .A2 ( n5 ) , .ZN ( n9 ) ) ;
OAI221_X1 U70 (.A ( n11 ) , .B1 ( n197 ) , .B2 ( n1 ) , .C1 ( n2 ) , .C2 ( n131 ) 
    , .ZN ( n241 ) ) ;
NAND2_X1 U71 (.A1 ( N360 ) , .A2 ( n5 ) , .ZN ( n11 ) ) ;
OAI221_X1 U72 (.A ( n13 ) , .B1 ( n198 ) , .B2 ( n1 ) , .C1 ( n2 ) , .C2 ( n153 ) 
    , .ZN ( n242 ) ) ;
NAND2_X1 U73 (.A1 ( N350 ) , .A2 ( n5 ) , .ZN ( n13 ) ) ;
OAI221_X1 U74 (.A ( n15 ) , .B1 ( n199 ) , .B2 ( n1 ) , .C1 ( n2 ) , .C2 ( n155 ) 
    , .ZN ( n243 ) ) ;
NAND2_X1 U75 (.A1 ( N340 ) , .A2 ( n5 ) , .ZN ( n15 ) ) ;
OAI221_X1 U76 (.A ( n17 ) , .B1 ( n200 ) , .B2 ( n1 ) , .C1 ( n2 ) , .C2 ( n156 ) 
    , .ZN ( n244 ) ) ;
NAND2_X1 U77 (.A1 ( N330 ) , .A2 ( n5 ) , .ZN ( n17 ) ) ;
OAI221_X1 U78 (.A ( n190 ) , .B1 ( n201 ) , .B2 ( n1 ) , .C1 ( n2 ) 
    , .C2 ( n157 ) , .ZN ( n245 ) ) ;
NAND2_X1 U79 (.A1 ( N320 ) , .A2 ( n5 ) , .ZN ( n190 ) ) ;
OAI221_X1 U80 (.A ( n21 ) , .B1 ( n202 ) , .B2 ( n1 ) , .C1 ( n2 ) , .C2 ( n158 ) 
    , .ZN ( n246 ) ) ;
NAND2_X1 U81 (.A1 ( N310 ) , .A2 ( n5 ) , .ZN ( n21 ) ) ;
OAI221_X1 U82 (.A ( n23 ) , .B1 ( n203 ) , .B2 ( n1 ) , .C1 ( n2 ) , .C2 ( n159 ) 
    , .ZN ( n247 ) ) ;
NAND2_X1 U83 (.A1 ( N303 ) , .A2 ( n5 ) , .ZN ( n23 ) ) ;
OAI221_X1 U84 (.A ( n25 ) , .B1 ( n204 ) , .B2 ( n1 ) , .C1 ( n2 ) , .C2 ( n161 ) 
    , .ZN ( n248 ) ) ;
NAND2_X1 U85 (.A1 ( N290 ) , .A2 ( n5 ) , .ZN ( n25 ) ) ;
OAI221_X1 U86 (.A ( n27 ) , .B1 ( n205 ) , .B2 ( n1 ) , .C1 ( n2 ) , .C2 ( n170 ) 
    , .ZN ( n249 ) ) ;
NAND2_X1 U87 (.A1 ( N280 ) , .A2 ( n5 ) , .ZN ( n27 ) ) ;
OAI221_X1 U88 (.A ( n29 ) , .B1 ( n206 ) , .B2 ( n1 ) , .C1 ( n2 ) , .C2 ( n172 ) 
    , .ZN ( n250 ) ) ;
NAND2_X1 U89 (.A1 ( N2710 ) , .A2 ( n5 ) , .ZN ( n29 ) ) ;
OAI221_X1 U90 (.A ( n31 ) , .B1 ( n207 ) , .B2 ( n1 ) , .C1 ( n2 ) , .C2 ( n173 ) 
    , .ZN ( n251 ) ) ;
NAND2_X1 U91 (.A1 ( N2610 ) , .A2 ( n5 ) , .ZN ( n31 ) ) ;
OAI221_X1 U92 (.A ( n124 ) , .B1 ( n215 ) , .B2 ( n122 ) , .C1 ( n216 ) 
    , .C2 ( n123 ) , .ZN ( n274 ) ) ;
OAI221_X1 U93 (.A ( n124 ) , .B1 ( n212 ) , .B2 ( n122 ) , .C1 ( n213 ) 
    , .C2 ( n123 ) , .ZN ( n277 ) ) ;
NOR2_X1 U94 (.A1 ( n99 ) , .A2 ( n160 ) , .ZN ( n117 ) ) ;
NAND3_X1 U95 (.A1 ( n235 ) , .A2 ( n44 ) , .A3 ( n101 ) , .ZN ( n57 ) ) ;
NAND2_X1 U96 (.A1 ( n180 ) , .A2 ( n124 ) , .ZN ( n80 ) ) ;
NAND4_X1 U97 (.A1 ( cmd[3] ) , .A2 ( n68 ) , .A3 ( n69 ) , .A4 ( n70 ) 
    , .ZN ( n67 ) ) ;
NOR2_X1 U98 (.A1 ( cmd[1] ) , .A2 ( n51 ) , .ZN ( n69 ) ) ;
OAI211_X1 U99 (.A ( n52 ) , .B ( n53 ) , .C1 ( n51 ) , .C2 ( n113 ) , .ZN ( n42 ) ) ;
AOI211_X1 U100 (.A ( n30 ) , .B ( n36 ) , .C1 ( din ) , .C2 ( n54 ) , .ZN ( n53 ) ) ;
OAI22_X1 U101 (.A1 ( n230 ) , .A2 ( n39 ) , .B1 ( n231 ) , .B2 ( n610 ) 
    , .ZN ( n264 ) ) ;
OAI22_X1 U102 (.A1 ( n231 ) , .A2 ( n39 ) , .B1 ( n610 ) , .B2 ( n72 ) 
    , .ZN ( n265 ) ) ;
OAI22_X1 U103 (.A1 ( n226 ) , .A2 ( n39 ) , .B1 ( n610 ) , .B2 ( n50 ) 
    , .ZN ( n260 ) ) ;
OAI22_X1 U104 (.A1 ( n222 ) , .A2 ( n39 ) , .B1 ( n610 ) , .B2 ( n58 ) 
    , .ZN ( n256 ) ) ;
OAI22_X1 U105 (.A1 ( n223 ) , .A2 ( n39 ) , .B1 ( n610 ) , .B2 ( n57 ) 
    , .ZN ( n257 ) ) ;
OAI22_X1 U106 (.A1 ( n233 ) , .A2 ( n39 ) , .B1 ( n610 ) , .B2 ( n74 ) 
    , .ZN ( n267 ) ) ;
OAI22_X1 U107 (.A1 ( n234 ) , .A2 ( n39 ) , .B1 ( n610 ) , .B2 ( n75 ) 
    , .ZN ( n268 ) ) ;
OAI22_X1 U108 (.A1 ( n235 ) , .A2 ( n39 ) , .B1 ( n610 ) , .B2 ( n47 ) 
    , .ZN ( n269 ) ) ;
OAI22_X1 U109 (.A1 ( n236 ) , .A2 ( n39 ) , .B1 ( n610 ) , .B2 ( n76 ) 
    , .ZN ( n270 ) ) ;
OAI21_X1 U110 (.A ( n77 ) , .B1 ( n237 ) , .B2 ( n39 ) , .ZN ( n271 ) ) ;
NAND4_X1 U111 (.A1 ( cmd[0] ) , .A2 ( n63 ) , .A3 ( n1180 ) , .A4 ( n114 ) 
    , .ZN ( n77 ) ) ;
INV_X1 U112 (.A ( cmd[2] ) , .ZN ( n114 ) ) ;
OAI21_X1 U113 (.A ( n73 ) , .B1 ( n232 ) , .B2 ( n39 ) , .ZN ( n266 ) ) ;
NAND3_X1 U114 (.A1 ( n68 ) , .A2 ( n63 ) , .A3 ( cmd[1] ) , .ZN ( n73 ) ) ;
OAI21_X1 U115 (.A ( n62 ) , .B1 ( n224 ) , .B2 ( n39 ) , .ZN ( n258 ) ) ;
NAND4_X1 U116 (.A1 ( cmd[2] ) , .A2 ( n63 ) , .A3 ( n116 ) , .A4 ( n1180 ) 
    , .ZN ( n62 ) ) ;
INV_X1 U117 (.A ( cmd[0] ) , .ZN ( n116 ) ) ;
NOR3_X1 U118 (.A1 ( n80 ) , .A2 ( n193 ) , .A3 ( n26 ) , .ZN ( N498 ) ) ;
INV_X1 U119 (.A ( n890 ) , .ZN ( n26 ) ) ;
OAI21_X1 U120 (.A ( n133 ) , .B1 ( n125 ) , .B2 ( n132 ) , .ZN ( N94 ) ) ;
NAND2_X1 U121 (.A1 ( N800 ) , .A2 ( n134 ) , .ZN ( n133 ) ) ;
OAI21_X1 U122 (.A ( n136 ) , .B1 ( n130 ) , .B2 ( n132 ) , .ZN ( N92 ) ) ;
NAND2_X1 U123 (.A1 ( N780 ) , .A2 ( n134 ) , .ZN ( n136 ) ) ;
OAI21_X1 U124 (.A ( n138 ) , .B1 ( n153 ) , .B2 ( n132 ) , .ZN ( N90 ) ) ;
NAND2_X1 U125 (.A1 ( N760 ) , .A2 ( n134 ) , .ZN ( n138 ) ) ;
OAI21_X1 U126 (.A ( n140 ) , .B1 ( n156 ) , .B2 ( n132 ) , .ZN ( N88 ) ) ;
NAND2_X1 U127 (.A1 ( N740 ) , .A2 ( n134 ) , .ZN ( n140 ) ) ;
OAI21_X1 U128 (.A ( n141 ) , .B1 ( n157 ) , .B2 ( n132 ) , .ZN ( N87 ) ) ;
DFFR_X1 cnt_reg_2_ (.D ( n251 ) , .RN ( nReset ) , .CK ( wb_clk_i_G1B2I16 ) 
    , .Q ( cnt[2] ) , .QN ( n207 ) ) ;
DFFR_X1 cnt_reg_3_ (.D ( n250 ) , .RN ( nReset ) , .CK ( wb_clk_i_G1B2I16 ) 
    , .Q ( cnt[3] ) , .QN ( n206 ) ) ;
DFFR_X1 cnt_reg_4_ (.D ( n249 ) , .RN ( nReset ) , .CK ( wb_clk_i_G1B2I16 ) 
    , .Q ( cnt[4] ) , .QN ( n205 ) ) ;
DFFR_X1 cnt_reg_5_ (.D ( n248 ) , .RN ( nReset ) , .CK ( wb_clk_i_G1B2I2 ) 
    , .Q ( cnt[5] ) , .QN ( n204 ) ) ;
DFFR_X1 cnt_reg_6_ (.D ( n247 ) , .RN ( nReset ) , .CK ( wb_clk_i_G1B2I2 ) 
    , .Q ( cnt[6] ) , .QN ( n203 ) ) ;
DFFR_X1 cnt_reg_7_ (.D ( n246 ) , .RN ( nReset ) , .CK ( wb_clk_i_G1B2I2 ) 
    , .Q ( cnt[7] ) , .QN ( n202 ) ) ;
DFFR_X1 cnt_reg_8_ (.D ( n245 ) , .RN ( nReset ) , .CK ( clk_cts_4 ) 
    , .Q ( cnt[8] ) , .QN ( n201 ) ) ;
DFFR_X1 cnt_reg_9_ (.D ( n244 ) , .RN ( nReset ) , .CK ( wb_clk_i_G1B2I22 ) 
    , .Q ( cnt[9] ) , .QN ( n200 ) ) ;
DFFR_X1 cnt_reg_10_ (.D ( n243 ) , .RN ( nReset ) , .CK ( clk_cts_4 ) 
    , .Q ( cnt[10] ) , .QN ( n199 ) ) ;
DFFR_X1 cnt_reg_11_ (.D ( n242 ) , .RN ( nReset ) , .CK ( clk_cts_4 ) 
    , .Q ( cnt[11] ) , .QN ( n198 ) ) ;
DFFR_X1 cnt_reg_12_ (.D ( n241 ) , .RN ( nReset ) , .CK ( wb_clk_i_G1B2I2 ) 
    , .Q ( cnt[12] ) , .QN ( n197 ) ) ;
DFFR_X1 cnt_reg_13_ (.D ( n240 ) , .RN ( nReset ) , .CK ( wb_clk_i_G1B2I16 ) 
    , .Q ( cnt[13] ) , .QN ( n196 ) ) ;
DFFR_X1 cnt_reg_14_ (.D ( n239 ) , .RN ( nReset ) , .CK ( wb_clk_i_G1B2I16 ) 
    , .Q ( cnt[14] ) , .QN ( n195 ) ) ;
DFFR_X1 cnt_reg_15_ (.D ( n238 ) , .RN ( nReset ) , .CK ( wb_clk_i_G1B2I16 ) 
    , .Q ( cnt[15] ) , .QN ( n194 ) ) ;
OAI33_X1 U213 (.A1 ( n1100 ) , .A2 ( n185 ) , .A3 ( n113 ) , .B1 ( n18 ) 
    , .B2 ( n28 ) , .B3 ( n24 ) , .ZN ( n169 ) ) ;
NOR2_X2 U39 (.A1 ( n32 ) , .A2 ( N218 ) , .ZN ( n5 ) ) ;
DFFS_X1 sSDA_reg (.D ( N110 ) , .SN ( nReset ) , .CK ( clk_cts_1 ) , .Q ( n185 ) 
    , .QN ( n16 ) ) ;
DFFS_X1 sSCL_reg (.D ( N109 ) , .SN ( nReset ) , .CK ( clk_cts_6 ) , .Q ( n186 ) 
    , .QN ( n12 ) ) ;
DFFS_X1 sda_oen_reg (.D ( n254 ) , .SN ( nReset ) , .CK ( wb_clk_i_G1B2I13 ) 
    , .Q ( sda_oen ) , .QN ( n113 ) ) ;
DFFS_X1 scl_oen_reg (.D ( n273 ) , .SN ( nReset ) , .CK ( clk_cts_3 ) 
    , .Q ( scl_oen ) , .QN ( n20 ) ) ;
DFFR_X1 sto_condition_reg (.D ( N1160 ) , .RN ( nReset ) , .CK ( clk_cts_1 ) 
    , .Q ( sto_condition ) , .QN ( n18 ) ) ;
DFFR_X1 slave_wait_reg (.D ( n299 ) , .RN ( nReset ) , .CK ( clk_cts_1_1 ) 
    , .QN ( n22 ) ) ;
DFFR_X1 filter_cnt_reg_4_ (.D ( N85 ) , .RN ( nReset ) 
    , .CK ( wb_clk_i_G1B2I22 ) , .Q ( filter_cnt[4] ) ) ;
DFFR_X1 filter_cnt_reg_3_ (.D ( N84 ) , .RN ( nReset ) 
    , .CK ( wb_clk_i_G1B2I22 ) , .Q ( filter_cnt[3] ) ) ;
DFFR_X1 filter_cnt_reg_2_ (.D ( N83 ) , .RN ( nReset ) , .CK ( clk_cts_0 ) 
    , .Q ( filter_cnt[2] ) ) ;
DFFR_X1 filter_cnt_reg_1_ (.D ( N820 ) , .RN ( nReset ) , .CK ( clk_cts_0 ) 
    , .Q ( filter_cnt[1] ) ) ;
DFFR_X1 filter_cnt_reg_0_ (.D ( N810 ) , .RN ( nReset ) , .CK ( clk_cts_6 ) 
    , .Q ( filter_cnt[0] ) ) ;
DFFR_X1 filter_cnt_reg_5_ (.D ( N86 ) , .RN ( nReset ) 
    , .CK ( wb_clk_i_G1B2I22 ) , .Q ( filter_cnt[5] ) ) ;
DFFR_X1 cmd_ack_reg (.D ( N498 ) , .RN ( nReset ) , .CK ( clk_cts_3_1 ) 
    , .Q ( cmd_ack ) ) ;
DFFR_X1 filter_cnt_reg_6_ (.D ( N87 ) , .RN ( nReset ) 
    , .CK ( wb_clk_i_G1B2I22 ) , .Q ( filter_cnt[6] ) ) ;
DFFR_X1 filter_cnt_reg_7_ (.D ( N88 ) , .RN ( nReset ) 
    , .CK ( wb_clk_i_G1B2I22 ) , .Q ( filter_cnt[7] ) ) ;
DFFR_X1 filter_cnt_reg_8_ (.D ( N89 ) , .RN ( nReset ) , .CK ( clk ) 
    , .Q ( filter_cnt[8] ) ) ;
DFFR_X1 filter_cnt_reg_9_ (.D ( N90 ) , .RN ( nReset ) 
    , .CK ( wb_clk_i_G1B2I22 ) , .Q ( filter_cnt[9] ) ) ;
DFFR_X1 filter_cnt_reg_10_ (.D ( N91 ) , .RN ( nReset ) , .CK ( clk_cts_0 ) 
    , .Q ( filter_cnt[10] ) ) ;
DFFR_X1 filter_cnt_reg_11_ (.D ( N92 ) , .RN ( nReset ) , .CK ( clk_cts_6 ) 
    , .Q ( filter_cnt[11] ) ) ;
DFFR_X1 filter_cnt_reg_12_ (.D ( N93 ) , .RN ( nReset ) , .CK ( clk_cts_0 ) 
    , .Q ( filter_cnt[12] ) ) ;
DFFR_X1 sda_chk_reg (.D ( n272 ) , .RN ( nReset ) , .CK ( wb_clk_i_G1B2I13 ) 
    , .QN ( n1100 ) ) ;
DFFR_X1 filter_cnt_reg_13_ (.D ( N94 ) , .RN ( nReset ) , .CK ( clk_cts_0 ) 
    , .Q ( filter_cnt[13] ) ) ;
DFFR_X1 cSDA_reg_1_ (.D ( N620 ) , .RN ( nReset ) , .CK ( clk_cts_6 ) 
    , .QN ( n210 ) ) ;
DFFR_X1 cSCL_reg_1_ (.D ( N60 ) , .RN ( nReset ) , .CK ( clk ) , .QN ( n211 ) ) ;
DFFR_X1 sta_condition_reg (.D ( N115 ) , .RN ( nReset ) , .CK ( clk_cts_2_1 ) 
    , .QN ( n177 ) ) ;
DFFR_X1 cSDA_reg_0_ (.D ( N61 ) , .RN ( nReset ) , .CK ( clk_cts_0 ) 
    , .QN ( n182 ) ) ;
DFFR_X1 cSCL_reg_0_ (.D ( N59 ) , .RN ( nReset ) , .CK ( wb_clk_i_G1B2I2 ) 
    , .QN ( n181 ) ) ;
DFFR_X1 cmd_stop_reg (.D ( n192 ) , .RN ( nReset ) , .CK ( clk_cts_0_1 ) 
    , .Q ( n24 ) ) ;
DFFR_X1 c_state_reg_9_ (.D ( n262 ) , .RN ( nReset ) , .CK ( wb_clk_i_G1B2I16 ) 
    , .Q ( n850 ) , .QN ( n228 ) ) ;
DFFR_X1 c_state_reg_16_ (.D ( n255 ) , .RN ( nReset ) 
    , .CK ( wb_clk_i_G1B2I13 ) , .Q ( n860 ) , .QN ( n221 ) ) ;
DFFR_X1 c_state_reg_15_ (.D ( n256 ) , .RN ( nReset ) 
    , .CK ( wb_clk_i_G1B2I13 ) , .Q ( n96 ) , .QN ( n222 ) ) ;
DFFR_X1 c_state_reg_14_ (.D ( n257 ) , .RN ( nReset ) 
    , .CK ( wb_clk_i_G1B2I13 ) , .Q ( n940 ) , .QN ( n223 ) ) ;
DFFR_X1 c_state_reg_12_ (.D ( n259 ) , .RN ( nReset ) , .CK ( clk_cts_8 ) 
    , .Q ( n1090 ) , .QN ( n225 ) ) ;
DFFR_X1 c_state_reg_11_ (.D ( n260 ) , .RN ( nReset ) , .CK ( clk_cts_9 ) 
    , .Q ( n98 ) , .QN ( n226 ) ) ;
DFFR_X1 c_state_reg_10_ (.D ( n261 ) , .RN ( nReset ) , .CK ( clk_cts_9 ) 
    , .Q ( n107 ) , .QN ( n227 ) ) ;
DFFR_X1 c_state_reg_8_ (.D ( n263 ) , .RN ( nReset ) , .CK ( clk_cts_8 ) 
    , .Q ( n105 ) , .QN ( n229 ) ) ;
DFFR_X1 c_state_reg_6_ (.D ( n265 ) , .RN ( nReset ) , .CK ( clk_cts_8 ) 
    , .Q ( n100 ) , .QN ( n231 ) ) ;
DFFR_X1 c_state_reg_4_ (.D ( n267 ) , .RN ( nReset ) , .CK ( wb_clk_i_G1B2I23 ) 
    , .Q ( n82 ) , .QN ( n233 ) ) ;
DFFR_X1 c_state_reg_3_ (.D ( n268 ) , .RN ( nReset ) , .CK ( wb_clk_i_G1B2I23 ) 
    , .Q ( n79 ) , .QN ( n234 ) ) ;
DFFR_X1 c_state_reg_2_ (.D ( n269 ) , .RN ( nReset ) , .CK ( wb_clk_i_G1B2I23 ) 
    , .Q ( n78 ) , .QN ( n235 ) ) ;
DFFR_X1 c_state_reg_1_ (.D ( n270 ) , .RN ( nReset ) , .CK ( clk_cts_9 ) 
    , .Q ( n64 ) , .QN ( n236 ) ) ;
DFFR_X1 c_state_reg_7_ (.D ( n264 ) , .RN ( nReset ) , .CK ( clk_cts_8 ) 
    , .Q ( n103 ) , .QN ( n230 ) ) ;
DFFR_X1 c_state_reg_5_ (.D ( n266 ) , .RN ( nReset ) , .CK ( wb_clk_i_G1B2I23 ) 
    , .Q ( n55 ) , .QN ( n232 ) ) ;
DFFR_X1 c_state_reg_13_ (.D ( n258 ) , .RN ( nReset ) 
    , .CK ( wb_clk_i_G1B2I13 ) , .Q ( n44 ) , .QN ( n224 ) ) ;
DFFR_X1 c_state_reg_0_ (.D ( n271 ) , .RN ( nReset ) , .CK ( wb_clk_i_G1B2I23 ) 
    , .Q ( n56 ) , .QN ( n237 ) ) ;
INV_X1 U3 (.A ( n32 ) , .ZN ( n1 ) ) ;
INV_X1 U4 (.A ( n70 ) , .ZN ( n610 ) ) ;
INV_X1 U5 (.A ( n76 ) , .ZN ( n30 ) ) ;
INV_X1 U6 (.A ( N218 ) , .ZN ( n2 ) ) ;
NOR2_X1 U7 (.A1 ( n22 ) , .A2 ( N218 ) , .ZN ( n32 ) ) ;
NOR3_X1 U8 (.A1 ( n56 ) , .A2 ( n103 ) , .A3 ( n99 ) , .ZN ( n930 ) ) ;
NOR2_X1 U9 (.A1 ( n55 ) , .A2 ( n82 ) , .ZN ( n106 ) ) ;
INV_X1 U10 (.A ( n122 ) , .ZN ( n123 ) ) ;
INV_X1 U11 (.A ( n39 ) , .ZN ( n41 ) ) ;
NOR2_X1 U12 (.A1 ( n850 ) , .A2 ( n105 ) , .ZN ( n95 ) ) ;
NOR2_X1 U13 (.A1 ( n80 ) , .A2 ( n41 ) , .ZN ( n70 ) ) ;
OAI22_X1 U14 (.A1 ( n113 ) , .A2 ( n39 ) , .B1 ( n40 ) , .B2 ( n41 ) 
    , .ZN ( n254 ) ) ;
NOR4_X1 U15 (.A1 ( n42 ) , .A2 ( n43 ) , .A3 ( n38 ) , .A4 ( n37 ) , .ZN ( n40 ) ) ;
INV_X1 U16 (.A ( n47 ) , .ZN ( n38 ) ) ;
OAI22_X1 U17 (.A1 ( n81 ) , .A2 ( n20 ) , .B1 ( n41 ) , .B2 ( n830 ) 
    , .ZN ( n273 ) ) ;
NOR3_X1 U18 (.A1 ( n41 ) , .A2 ( n28 ) , .A3 ( n30 ) , .ZN ( n81 ) ) ;
INV_X1 U19 (.A ( n48 ) , .ZN ( n34 ) ) ;
OAI21_X1 U20 (.A ( n137 ) , .B1 ( n131 ) , .B2 ( n132 ) , .ZN ( N91 ) ) ;
NAND2_X1 U21 (.A1 ( N770 ) , .A2 ( n134 ) , .ZN ( n137 ) ) ;
OAI21_X1 U22 (.A ( n139 ) , .B1 ( n155 ) , .B2 ( n132 ) , .ZN ( N89 ) ) ;
NAND2_X1 U23 (.A1 ( N750 ) , .A2 ( n134 ) , .ZN ( n139 ) ) ;
OAI21_X1 U24 (.A ( n147 ) , .B1 ( n173 ) , .B2 ( n132 ) , .ZN ( N810 ) ) ;
NAND2_X1 U25 (.A1 ( N670 ) , .A2 ( n134 ) , .ZN ( n147 ) ) ;
NAND2_X1 U26 (.A1 ( n117 ) , .A2 ( n56 ) , .ZN ( n76 ) ) ;
NAND3_X1 U27 (.A1 ( n48 ) , .A2 ( n49 ) , .A3 ( n50 ) , .ZN ( n43 ) ) ;
INV_X1 U28 (.A ( n80 ) , .ZN ( n52 ) ) ;
INV_X1 U29 (.A ( n66 ) , .ZN ( n36 ) ) ;
INV_X1 U30 (.A ( n51 ) , .ZN ( n28 ) ) ;
NAND4_X1 U31 (.A1 ( n57 ) , .A2 ( n76 ) , .A3 ( n51 ) , .A4 ( n72 ) 
    , .ZN ( n880 ) ) ;
NOR2_X1 U32 (.A1 ( n148 ) , .A2 ( rst ) , .ZN ( n122 ) ) ;
NAND2_X1 U33 (.A1 ( n122 ) , .A2 ( ena ) , .ZN ( n132 ) ) ;
AND3_X1 U34 (.A1 ( n148 ) , .A2 ( n124 ) , .A3 ( ena ) , .ZN ( n134 ) ) ;
DFFS_X1 fSCL_reg_0_ (.D ( n279 ) , .SN ( nReset ) , .CK ( clk ) , .QN ( n214 ) ) ;
DFFS_X1 fSCL_reg_1_ (.D ( n278 ) , .SN ( nReset ) , .CK ( clk ) , .QN ( n213 ) ) ;
DFFS_X1 fSCL_reg_2_ (.D ( n277 ) , .SN ( nReset ) , .CK ( clk ) , .QN ( n212 ) ) ;
DFFS_X1 fSDA_reg_0_ (.D ( n276 ) , .SN ( nReset ) , .CK ( clk_cts_6 ) 
    , .QN ( n217 ) ) ;
DFFS_X1 fSDA_reg_1_ (.D ( n275 ) , .SN ( nReset ) , .CK ( clk_cts_6 ) 
    , .QN ( n216 ) ) ;
DFFS_X1 fSDA_reg_2_ (.D ( n274 ) , .SN ( nReset ) , .CK ( clk ) , .QN ( n215 ) ) ;
SDFFS_X1 dSCL_reg (.D ( 1'b1 ), .SE ( n302 ) , .SI ( rst ) , .SN ( nReset ) 
    , .CK ( clk_cts_2_1 ) , .QN ( n187 ) ) ;
SDFFS_X1 dSDA_reg (.D ( 1'b1 ), .SE ( n16 ) , .SI ( rst ) , .SN ( nReset ) 
    , .CK ( clk_cts_2_1 ) , .QN ( n220 ) ) ;
DFFR_X1 busy_reg (.D ( N118 ) , .RN ( nReset ) , .CK ( clk_cts_1 ) , .Q ( busy ) 
    , .QN ( n178 ) ) ;
DFF_X1 dout_reg (.D ( n189 ) , .CK ( clk_cts_5 ) , .Q ( dout ) , .QN ( n188 ) ) ;
DFF_X1 dscl_oen_reg (.D ( scl_oen ) , .CK ( clk_cts_3 ) , .QN ( n179 ) ) ;
DFFS_X1 clk_en_reg (.D ( N218 ) , .SN ( nReset ) , .CK ( clk_cts_2 ) 
    , .QN ( n193 ) ) ;
DFFR_X1 al_reg (.D ( N1230 ) , .RN ( nReset ) , .CK ( clk_cts_3_1 ) , .Q ( al ) 
    , .QN ( n180 ) ) ;
DFFR_X1 cnt_reg_0_ (.D ( n253 ) , .RN ( nReset ) , .CK ( clk_cts_9 ) 
    , .Q ( cnt[0] ) , .QN ( n209 ) ) ;
DFFR_X1 cnt_reg_1_ (.D ( n252 ) , .RN ( nReset ) , .CK ( wb_clk_i_G1B2I16 ) 
    , .Q ( cnt[1] ) , .QN ( n208 ) ) ;
endmodule




module i2c_master_byte_ctrl (scl_oen , sda_o , sda_oen , clk_cts_0 , 
    clk_cts_1 , clk_cts_2 , ack_in , scl_i , sda_i , cmd_ack , ack_out , 
    i2c_busy , i2c_al , scl_o , clk , rst , nReset , ena , start , 
    stop , read , write , dout , din , clk_cnt , clk_cts_3 , 
    clk_cts_4 , clk_cts_5 , clk_cts_6 , clk_cts_7 , clk_cts_8 , 
    clk_cts_0_1 , clk_cts_1_1 , clk_cts_2_1 , clk_cts_3_1 , clk_cts_4_1 , 
    clk_cts_5_1 , clk_cts_7_1 , clk_cts_8_1 , clk_cts_9_1 , cts_0 );
output scl_oen ;
output sda_o ;
output sda_oen ;
input  clk_cts_0 ;
input  clk_cts_1 ;
input  clk_cts_2 ;
input  ack_in ;
input  scl_i ;
input  sda_i ;
output cmd_ack ;
output ack_out ;
output i2c_busy ;
output i2c_al ;
output scl_o ;
input  clk ;
input  rst ;
input  nReset ;
input  ena ;
input  start ;
input  stop ;
input  read ;
input  write ;
output [7:0] dout ;
input  [7:0] din ;
input  [15:0] clk_cnt ;
input  clk_cts_3 ;
input  clk_cts_4 ;
input  clk_cts_5 ;
input  clk_cts_6 ;
input  clk_cts_7 ;
input  clk_cts_8 ;
input  clk_cts_0_1 ;
input  clk_cts_1_1 ;
input  clk_cts_2_1 ;
input  clk_cts_3_1 ;
input  clk_cts_4_1 ;
input  clk_cts_5_1 ;
input  clk_cts_7_1 ;
input  clk_cts_8_1 ;
input  clk_cts_9_1 ;
input  cts_0 ;

wire [3:0] core_cmd ;

wire [4:0] c_state ;


i2c_master_bit_ctrl bit_controller (.scl_oen ( scl_oen ) , 
    .sda_oen ( sda_oen ) , .clk_cts_0 ( clk_cts_0 ) , .clk_cts_1 ( clk_cts_1 ) , 
    .clk_cts_2 ( clk_cts_2 ) , .din ( core_txd ) , .scl_i ( scl_i ) , 
    .sda_i ( sda_i ) , .cmd_ack ( core_ack ) , .busy ( i2c_busy ) , 
    .al ( i2c_al ) , .dout ( core_rxd ) , .cmd ( core_cmd ) , .clk ( clk ) , 
    .rst ( rst ) , .nReset ( nReset ) , .ena ( ena ) , .clk_cnt ( clk_cnt ) , 
    .clk_cts_3 ( clk_cts_3 ) , .clk_cts_4 ( clk_cts_4 ) , 
    .clk_cts_5 ( clk_cts_6 ) , .clk_cts_6 ( clk_cts_8 ) , 
    .clk_cts_8 ( clk_cts_0_1 ) , .clk_cts_9 ( clk_cts_1_1 ) , 
    .clk_cts_0_1 ( clk_cts_2_1 ) , .clk_cts_1_1 ( clk_cts_3_1 ) , 
    .clk_cts_2_1 ( wb_clk_i_G1B2I4 ) , .clk_cts_3_1 ( clk_cts_4_1 ) , 
    .clk_cts_5_1 ( clk_cts_7_1 ) , .clk_cts_6_1 ( clk_cts_8_1 ) , 
    .cts_0 ( cts_0 ) ) ;

CLKBUF_X2 CLKBUF_X1_G1B1I4 (.A ( clk_cts_9_1 ) , .Z ( wb_clk_i_G1B2I4 ) ) ;
INV_X1 U22 (.A ( n69 ) , .ZN ( n25 ) ) ;
AOI21_X1 U23 (.A ( n84 ) , .B1 ( n67 ) , .B2 ( n89 ) , .ZN ( N129 ) ) ;
NAND2_X1 U24 (.A1 ( n23 ) , .A2 ( n70 ) , .ZN ( n89 ) ) ;
NOR2_X1 U25 (.A1 ( n83 ) , .A2 ( n84 ) , .ZN ( N131 ) ) ;
AOI21_X1 U26 (.A ( n82 ) , .B1 ( n22 ) , .B2 ( n36 ) , .ZN ( n83 ) ) ;
NOR2_X1 U27 (.A1 ( n34 ) , .A2 ( rst ) , .ZN ( n41 ) ) ;
NAND4_X1 U28 (.A1 ( c_state[1] ) , .A2 ( n90 ) , .A3 ( n29 ) , .A4 ( n28 ) 
    , .ZN ( n67 ) ) ;
NOR4_X1 U29 (.A1 ( c_state[1] ) , .A2 ( c_state[2] ) , .A3 ( c_state[3] ) 
    , .A4 ( c_state[4] ) , .ZN ( n88 ) ) ;
NAND4_X1 U30 (.A1 ( c_state[3] ) , .A2 ( n90 ) , .A3 ( n30 ) , .A4 ( n29 ) 
    , .ZN ( n76 ) ) ;
NOR2_X1 U31 (.A1 ( i2c_al ) , .A2 ( rst ) , .ZN ( n74 ) ) ;
NAND3_X1 U32 (.A1 ( n34 ) , .A2 ( n35 ) , .A3 ( shift ) , .ZN ( n49 ) ) ;
AOI221_X1 U33 (.A ( n38 ) , .B1 ( dout[7] ) , .B2 ( n92 ) , .C1 ( ack_in ) 
    , .C2 ( n93 ) , .ZN ( n91 ) ) ;
OAI21_X1 U34 (.A ( n76 ) , .B1 ( n6 ) , .B2 ( n67 ) , .ZN ( n93 ) ) ;
OAI22_X1 U35 (.A1 ( n22 ) , .A2 ( n24 ) , .B1 ( core_ack ) , .B2 ( n67 ) 
    , .ZN ( n92 ) ) ;
NOR2_X1 U36 (.A1 ( c_state[4] ) , .A2 ( c_state[0] ) , .ZN ( n90 ) ) ;
NOR2_X1 U37 (.A1 ( n78 ) , .A2 ( start ) , .ZN ( n65 ) ) ;
NAND4_X1 U38 (.A1 ( c_state[2] ) , .A2 ( n90 ) , .A3 ( n30 ) , .A4 ( n28 ) 
    , .ZN ( n63 ) ) ;
OAI21_X1 U39 (.A ( n60 ) , .B1 ( n49 ) , .B2 ( n19 ) , .ZN ( n59 ) ) ;
NAND3_X1 U40 (.A1 ( n17 ) , .A2 ( n16 ) , .A3 ( n19 ) , .ZN ( n70 ) ) ;
OAI22_X1 U41 (.A1 ( n53 ) , .A2 ( n57 ) , .B1 ( n3 ) , .B2 ( n32 ) , .ZN ( n104 ) ) ;
OAI22_X1 U42 (.A1 ( n53 ) , .A2 ( n57 ) , .B1 ( n21 ) , .B2 ( n3 ) , .ZN ( n113 ) ) ;
OAI221_X1 U43 (.A ( n33 ) , .B1 ( n49 ) , .B2 ( n70 ) , .C1 ( n73 ) , .C2 ( n16 ) 
    , .ZN ( n112 ) ) ;
AOI21_X1 U44 (.A ( n59 ) , .B1 ( dcnt_1_ ) , .B2 ( n20 ) , .ZN ( n73 ) ) ;
OAI221_X1 U45 (.A ( n33 ) , .B1 ( dcnt_1_ ) , .B2 ( n58 ) , .C1 ( n18 ) 
    , .C2 ( n17 ) , .ZN ( n105 ) ) ;
INV_X1 U46 (.A ( n59 ) , .ZN ( n18 ) ) ;
NOR2_X1 U47 (.A1 ( cmd_ack ) , .A2 ( n87 ) , .ZN ( n80 ) ) ;
NOR3_X1 U48 (.A1 ( read ) , .A2 ( write ) , .A3 ( stop ) , .ZN ( n87 ) ) ;
NAND3_X1 U49 (.A1 ( n61 ) , .A2 ( n26 ) , .A3 ( start ) , .ZN ( n71 ) ) ;
NAND2_X1 U50 (.A1 ( n74 ) , .A2 ( core_ack ) , .ZN ( n84 ) ) ;
OAI21_X1 U51 (.A ( n40 ) , .B1 ( n39 ) , .B2 ( n7 ) , .ZN ( n94 ) ) ;
AOI22_X1 U52 (.A1 ( dout[6] ) , .A2 ( n20 ) , .B1 ( din[7] ) , .B2 ( n41 ) 
    , .ZN ( n40 ) ) ;
OAI21_X1 U53 (.A ( n43 ) , .B1 ( n39 ) , .B2 ( n9 ) , .ZN ( n96 ) ) ;
AOI22_X1 U54 (.A1 ( dout[4] ) , .A2 ( n20 ) , .B1 ( din[5] ) , .B2 ( n41 ) 
    , .ZN ( n43 ) ) ;
OAI21_X1 U55 (.A ( n44 ) , .B1 ( n39 ) , .B2 ( n10 ) , .ZN ( n97 ) ) ;
AOI22_X1 U56 (.A1 ( dout[3] ) , .A2 ( n20 ) , .B1 ( din[4] ) , .B2 ( n41 ) 
    , .ZN ( n44 ) ) ;
OAI21_X1 U57 (.A ( n45 ) , .B1 ( n39 ) , .B2 ( n11 ) , .ZN ( n98 ) ) ;
AOI22_X1 U59 (.A1 ( dout[2] ) , .A2 ( n20 ) , .B1 ( din[3] ) , .B2 ( n41 ) 
    , .ZN ( n45 ) ) ;
OAI21_X1 U60 (.A ( n46 ) , .B1 ( n39 ) , .B2 ( n12 ) , .ZN ( n99 ) ) ;
AOI22_X1 U61 (.A1 ( dout[1] ) , .A2 ( n20 ) , .B1 ( din[2] ) , .B2 ( n41 ) 
    , .ZN ( n46 ) ) ;
OAI21_X1 U62 (.A ( n47 ) , .B1 ( n39 ) , .B2 ( n13 ) , .ZN ( n100 ) ) ;
AOI22_X1 U63 (.A1 ( dout[0] ) , .A2 ( n20 ) , .B1 ( din[1] ) , .B2 ( n41 ) 
    , .ZN ( n47 ) ) ;
OAI21_X1 U64 (.A ( n48 ) , .B1 ( n39 ) , .B2 ( n14 ) , .ZN ( n101 ) ) ;
AOI22_X1 U65 (.A1 ( n20 ) , .A2 ( core_rxd ) , .B1 ( din[0] ) , .B2 ( n41 ) 
    , .ZN ( n48 ) ) ;
NAND2_X1 U66 (.A1 ( n88 ) , .A2 ( n31 ) , .ZN ( n78 ) ) ;
NAND2_X1 U67 (.A1 ( c_state[0] ) , .A2 ( n88 ) , .ZN ( n69 ) ) ;
AOI22_X1 U68 (.A1 ( core_rxd ) , .A2 ( n38 ) , .B1 ( ack_out ) , .B2 ( n5 ) 
    , .ZN ( n37 ) ) ;
INV_X1 U69 (.A ( n38 ) , .ZN ( n5 ) ) ;
OR3_X1 U70 (.A1 ( n81 ) , .A2 ( n23 ) , .A3 ( n82 ) , .ZN ( n79 ) ) ;
NAND3_X1 U71 (.A1 ( n67 ) , .A2 ( n76 ) , .A3 ( n69 ) , .ZN ( n81 ) ) ;
NAND2_X1 U72 (.A1 ( n20 ) , .A2 ( n19 ) , .ZN ( n58 ) ) ;
NAND2_X1 U73 (.A1 ( n61 ) , .A2 ( n62 ) , .ZN ( n54 ) ) ;
OAI22_X1 U74 (.A1 ( n15 ) , .A2 ( n63 ) , .B1 ( read ) , .B2 ( n64 ) 
    , .ZN ( n62 ) ) ;
AOI21_X1 U75 (.A ( n25 ) , .B1 ( write ) , .B2 ( n65 ) , .ZN ( n64 ) ) ;
NAND2_X1 U76 (.A1 ( n61 ) , .A2 ( n66 ) , .ZN ( n50 ) ) ;
OAI21_X1 U77 (.A ( n68 ) , .B1 ( n15 ) , .B2 ( n67 ) , .ZN ( n66 ) ) ;
OAI21_X1 U78 (.A ( read ) , .B1 ( n65 ) , .B2 ( n25 ) , .ZN ( n68 ) ) ;
OAI211_X1 U79 (.A ( n58 ) , .B ( n33 ) , .C1 ( n19 ) , .C2 ( n60 ) , .ZN ( n106 ) ) ;
OAI211_X1 U80 (.A ( n55 ) , .B ( n51 ) , .C1 ( n28 ) , .C2 ( n3 ) , .ZN ( n107 ) ) ;
OAI21_X1 U81 (.A ( n42 ) , .B1 ( n8 ) , .B2 ( n39 ) , .ZN ( n95 ) ) ;
AOI22_X1 U82 (.A1 ( dout[5] ) , .A2 ( n20 ) , .B1 ( din[6] ) , .B2 ( n41 ) 
    , .ZN ( n42 ) ) ;
OAI21_X1 U83 (.A ( n50 ) , .B1 ( n30 ) , .B2 ( n3 ) , .ZN ( n109 ) ) ;
OAI21_X1 U84 (.A ( n71 ) , .B1 ( n31 ) , .B2 ( n3 ) , .ZN ( n110 ) ) ;
OAI21_X1 U85 (.A ( n54 ) , .B1 ( n29 ) , .B2 ( n3 ) , .ZN ( n108 ) ) ;
AND4_X1 U86 (.A1 ( c_state[4] ) , .A2 ( n31 ) , .A3 ( n85 ) , .A4 ( n30 ) 
    , .ZN ( n82 ) ) ;
NOR2_X1 U87 (.A1 ( c_state[3] ) , .A2 ( c_state[2] ) , .ZN ( n85 ) ) ;
INV_X1 U88 (.A ( core_ack ) , .ZN ( n6 ) ) ;
INV_X1 U89 (.A ( stop ) , .ZN ( n36 ) ) ;
NAND3_X1 U90 (.A1 ( n54 ) , .A2 ( n55 ) , .A3 ( n56 ) , .ZN ( n103 ) ) ;
NAND2_X1 U91 (.A1 ( core_cmd[2] ) , .A2 ( n53 ) , .ZN ( n56 ) ) ;
NAND3_X1 U92 (.A1 ( n50 ) , .A2 ( n51 ) , .A3 ( n52 ) , .ZN ( n102 ) ) ;
NAND2_X1 U93 (.A1 ( core_cmd[3] ) , .A2 ( n53 ) , .ZN ( n52 ) ) ;
NAND2_X1 U94 (.A1 ( n74 ) , .A2 ( n75 ) , .ZN ( n57 ) ) ;
OAI22_X1 U95 (.A1 ( n76 ) , .A2 ( n36 ) , .B1 ( n27 ) , .B2 ( n77 ) , .ZN ( n75 ) ) ;
OR2_X1 U96 (.A1 ( read ) , .A2 ( write ) , .ZN ( n77 ) ) ;
INV_X1 U97 (.A ( n65 ) , .ZN ( n27 ) ) ;
NAND2_X1 U98 (.A1 ( n71 ) , .A2 ( n72 ) , .ZN ( n111 ) ) ;
NAND2_X1 U99 (.A1 ( core_cmd[0] ) , .A2 ( n53 ) , .ZN ( n72 ) ) ;
INV_X1 U100 (.A ( rst ) , .ZN ( n35 ) ) ;
SDFFR_X1 core_txd_reg (.D ( n74 ) , .RN ( nReset ) , .SE ( n91 ) , .SI ( 1'b0 )
    , .CK ( clk_cts_5_1 ) , .Q ( core_txd ) ) ;
DFFR_X1 c_state_reg_1_ (.D ( n109 ) , .RN ( nReset ) , .CK ( wb_clk_i_G1B2I4 ) 
    , .Q ( c_state[1] ) , .QN ( n30 ) ) ;
DFFR_X1 c_state_reg_4_ (.D ( n113 ) , .RN ( nReset ) , .CK ( clk_cts_1 ) 
    , .Q ( c_state[4] ) , .QN ( n21 ) ) ;
DFFR_X1 c_state_reg_3_ (.D ( n107 ) , .RN ( nReset ) , .CK ( clk_cts_7 ) 
    , .Q ( c_state[3] ) , .QN ( n28 ) ) ;
DFFR_X1 c_state_reg_2_ (.D ( n108 ) , .RN ( nReset ) , .CK ( clk_cts_7 ) 
    , .Q ( c_state[2] ) , .QN ( n29 ) ) ;
DFFR_X1 c_state_reg_0_ (.D ( n110 ) , .RN ( nReset ) , .CK ( wb_clk_i_G1B2I4 ) 
    , .Q ( c_state[0] ) , .QN ( n31 ) ) ;
DFFR_X1 dcnt_reg_1_ (.D ( n105 ) , .RN ( nReset ) , .CK ( clk_cts_6 ) 
    , .Q ( dcnt_1_ ) , .QN ( n17 ) ) ;
DFFR_X1 sr_reg_0_ (.D ( n101 ) , .RN ( nReset ) , .CK ( clk_cts_3_1 ) 
    , .Q ( dout[0] ) , .QN ( n14 ) ) ;
DFFR_X1 sr_reg_1_ (.D ( n100 ) , .RN ( nReset ) , .CK ( clk_cts_3 ) 
    , .Q ( dout[1] ) , .QN ( n13 ) ) ;
DFFR_X1 sr_reg_2_ (.D ( n99 ) , .RN ( nReset ) , .CK ( clk_cts_3 ) 
    , .Q ( dout[2] ) , .QN ( n12 ) ) ;
DFFR_X1 sr_reg_3_ (.D ( n98 ) , .RN ( nReset ) , .CK ( clk_cts_3 ) 
    , .Q ( dout[3] ) , .QN ( n11 ) ) ;
DFFR_X1 sr_reg_4_ (.D ( n97 ) , .RN ( nReset ) , .CK ( clk_cts_5 ) 
    , .Q ( dout[4] ) , .QN ( n10 ) ) ;
DFFR_X1 sr_reg_5_ (.D ( n96 ) , .RN ( nReset ) , .CK ( clk_cts_5 ) 
    , .Q ( dout[5] ) , .QN ( n9 ) ) ;
DFFR_X1 sr_reg_6_ (.D ( n95 ) , .RN ( nReset ) , .CK ( clk_cts_3_1 ) 
    , .Q ( dout[6] ) , .QN ( n8 ) ) ;
DFFR_X1 sr_reg_7_ (.D ( n94 ) , .RN ( nReset ) , .CK ( clk_cts_6 ) 
    , .Q ( dout[7] ) , .QN ( n7 ) ) ;
DFFR_X1 core_cmd_reg_1_ (.D ( n104 ) , .RN ( nReset ) , .CK ( clk_cts_0 ) 
    , .Q ( core_cmd[1] ) , .QN ( n32 ) ) ;
SDFFR_X1 ack_out_reg (.D ( n74 ) , .RN ( nReset ) , .SE ( n37 ) , .SI ( 1'b0 )
    , .CK ( clk_cts_5_1 ) , .Q ( ack_out ) ) ;
AOI221_X2 U58 (.A ( n4 ) , .B1 ( n79 ) , .B2 ( core_ack ) , .C1 ( n26 ) 
    , .C2 ( n80 ) , .ZN ( n53 ) ) ;
DFFR_X1 shift_reg (.D ( N129 ) , .RN ( nReset ) , .CK ( clk_cts_7 ) 
    , .Q ( shift ) ) ;
DFFR_X1 cmd_ack_reg (.D ( N131 ) , .RN ( nReset ) , .CK ( clk_cts_5_1 ) 
    , .Q ( cmd_ack ) ) ;
DFFR_X1 core_cmd_reg_0_ (.D ( n111 ) , .RN ( nReset ) , .CK ( clk_cts_5_1 ) 
    , .Q ( core_cmd[0] ) ) ;
DFFR_X1 core_cmd_reg_2_ (.D ( n103 ) , .RN ( nReset ) , .CK ( clk_cts_1 ) 
    , .Q ( core_cmd[2] ) ) ;
DFFR_X1 core_cmd_reg_3_ (.D ( n102 ) , .RN ( nReset ) , .CK ( clk_cts_1 ) 
    , .Q ( core_cmd[3] ) ) ;
DFFR_X1 dcnt_reg_0_ (.D ( n106 ) , .RN ( nReset ) , .CK ( clk_cts_7 ) 
    , .QN ( n19 ) ) ;
DFFR_X1 dcnt_reg_2_ (.D ( n112 ) , .RN ( nReset ) , .CK ( clk_cts_7 ) 
    , .QN ( n16 ) ) ;
DFFR_X1 ld_reg (.D ( N130 ) , .RN ( nReset ) , .CK ( clk_cts_7 ) , .QN ( n34 ) ) ;
NAND3_X1 U5 (.A1 ( n61 ) , .A2 ( n15 ) , .A3 ( n24 ) , .ZN ( n55 ) ) ;
NAND3_X1 U6 (.A1 ( n23 ) , .A2 ( n15 ) , .A3 ( n61 ) , .ZN ( n51 ) ) ;
NAND3_X1 U7 (.A1 ( n33 ) , .A2 ( n35 ) , .A3 ( n49 ) , .ZN ( n39 ) ) ;
NOR2_X1 U8 (.A1 ( n4 ) , .A2 ( n53 ) , .ZN ( n61 ) ) ;
INV_X1 U9 (.A ( n49 ) , .ZN ( n20 ) ) ;
INV_X1 U10 (.A ( n53 ) , .ZN ( n3 ) ) ;
NOR2_X1 U11 (.A1 ( n6 ) , .A2 ( n76 ) , .ZN ( n38 ) ) ;
INV_X1 U12 (.A ( n41 ) , .ZN ( n33 ) ) ;
INV_X1 U13 (.A ( n67 ) , .ZN ( n24 ) ) ;
INV_X1 U14 (.A ( n70 ) , .ZN ( n15 ) ) ;
INV_X1 U15 (.A ( n76 ) , .ZN ( n22 ) ) ;
NAND2_X1 U16 (.A1 ( n49 ) , .A2 ( n35 ) , .ZN ( n60 ) ) ;
INV_X1 U17 (.A ( n63 ) , .ZN ( n23 ) ) ;
INV_X1 U18 (.A ( n78 ) , .ZN ( n26 ) ) ;
INV_X1 U19 (.A ( n74 ) , .ZN ( n4 ) ) ;
OAI21_X1 U20 (.A ( n86 ) , .B1 ( n84 ) , .B2 ( n69 ) , .ZN ( N130 ) ) ;
NAND3_X1 U21 (.A1 ( n26 ) , .A2 ( n74 ) , .A3 ( n80 ) , .ZN ( n86 ) ) ;
endmodule




module i2c_master_top (wb_adr_i , wb_dat_i , wb_dat_o , wb_cyc_i , 
    wb_stb_i , wb_we_i , arst_i , wb_rst_i , wb_clk_i , sda_padoen_o , 
    sda_pad_o , scl_padoen_o , scl_pad_o , wb_inta_o , wb_ack_o , 
    sda_pad_i , scl_pad_i );
input  [2:0] wb_adr_i ;
input  [7:0] wb_dat_i ;
output [7:0] wb_dat_o ;
input  wb_cyc_i ;
input  wb_stb_i ;
input  wb_we_i ;
input  arst_i ;
input  wb_rst_i ;
input  wb_clk_i ;
output sda_padoen_o ;
output sda_pad_o ;
output scl_padoen_o ;
output scl_pad_o ;
output wb_inta_o ;
output wb_ack_o ;
input  sda_pad_i ;
input  scl_pad_i ;

wire [7:0] cr ;
wire [7:5] sr ;
wire [7:0] ctr ;
wire [7:0] rxr ;
wire [7:0] txr ;
wire [15:0] prer ;


assign scl_pad_o = sda_pad_o ;

i2c_master_byte_ctrl byte_controller (.scl_oen ( scl_padoen_o ) , 
    .sda_oen ( sda_padoen_o ) , .clk_cts_0 ( wb_clk_i_G1B2I21 ) , 
    .clk_cts_1 ( wb_clk_i_G1B2I20 ) , .clk_cts_2 ( wb_clk_i_G1B2I18 ) , 
    .ack_in ( cr[3] ) , .scl_i ( scl_pad_i ) , .sda_i ( sda_pad_i ) , 
    .cmd_ack ( done ) , .ack_out ( irxack ) , .i2c_busy ( sr[6] ) , 
    .i2c_al ( i2c_al ) , .clk ( wb_clk_i_G1B2I9 ) , .rst ( wb_rst_i ) , 
    .nReset ( arst_i ) , .ena ( ctr[7] ) , .start ( cr[7] ) , .stop ( cr[6] ) , 
    .read ( cr[5] ) , .write ( cr[4] ) , .dout ( rxr ) , .din ( txr ) , 
    .clk_cnt ( prer ) , .clk_cts_3 ( wb_clk_i_G1B2I17 ) , 
    .clk_cts_4 ( wb_clk_i_G1B2I15 ) , .clk_cts_5 ( wb_clk_i_G1B2I14 ) , 
    .clk_cts_6 ( wb_clk_i_G1B2I12 ) , .clk_cts_7 ( wb_clk_i_G1B2I11 ) , 
    .clk_cts_8 ( wb_clk_i_G1B2I10 ) , .clk_cts_0_1 ( wb_clk_i_G1B2I8 ) , 
    .clk_cts_1_1 ( wb_clk_i_G1B2I7 ) , .clk_cts_2_1 ( wb_clk_i_G1B2I6 ) , 
    .clk_cts_3_1 ( wb_clk_i_G1B2I5 ) , .clk_cts_4_1 ( wb_clk_i_G1B2I3 ) , 
    .clk_cts_5_1 ( wb_clk_i_G1B2I1 ) , .clk_cts_7_1 ( wb_clk_i_G1B1I3 ) , 
    .clk_cts_8_1 ( wb_clk_i_G1B1I2 ) , .clk_cts_9_1 ( wb_clk_i_G1B1I1 ) , 
    .cts_0 ( wb_clk_i ) ) ;

BUF_X1 U2 (.A ( n480 ) , .Z ( n169 ) ) ;
BUF_X1 U1 (.A ( n9 ) , .Z ( n168 ) ) ;
CLKBUF_X1 CLKBUF_X1_G1B2I3 (.A ( wb_clk_i ) , .Z ( wb_clk_i_G1B1I3 ) ) ;
CLKBUF_X1 CLKBUF_X1_G1B2I1 (.A ( wb_clk_i ) , .Z ( wb_clk_i_G1B1I1 ) ) ;
CLKBUF_X2 CLKBUF_X1_G1B2I2 (.A ( wb_clk_i ) , .Z ( wb_clk_i_G1B1I2 ) ) ;
CLKBUF_X1 CLKBUF_X1_G1B1I14_1 (.A ( wb_clk_i_G1B1I2 ) 
    , .Z ( wb_clk_i_G1B2I14 ) ) ;
CLKBUF_X1 CLKBUF_X1_G1B1I6 (.A ( wb_clk_i_G1B1I2 ) , .Z ( wb_clk_i_G1B2I6 ) ) ;
CLKBUF_X2 CLKBUF_X1_G1B1I19 (.A ( wb_clk_i_G1B1I2 ) , .Z ( wb_clk_i_G1B2I19 ) ) ;
CLKBUF_X2 CLKBUF_X1_G1B1I17 (.A ( wb_clk_i_G1B1I2 ) , .Z ( wb_clk_i_G1B2I17 ) ) ;
CLKBUF_X1 CLKBUF_X1_G1B1I8 (.A ( wb_clk_i_G1B1I3 ) , .Z ( wb_clk_i_G1B2I8 ) ) ;
CLKBUF_X2 CLKBUF_X1_G1B1I12_1 (.A ( wb_clk_i_G1B1I1 ) 
    , .Z ( wb_clk_i_G1B2I12 ) ) ;
CLKBUF_X2 CLKBUF_X1_G1B1I20 (.A ( wb_clk_i_G1B1I1 ) , .Z ( wb_clk_i_G1B2I20 ) ) ;
CLKBUF_X2 CLKBUF_X1_G1B1I5 (.A ( wb_clk_i_G1B1I1 ) , .Z ( wb_clk_i_G1B2I5 ) ) ;
CLKBUF_X2 CLKBUF_X1_G1B1I11 (.A ( wb_clk_i_G1B1I1 ) , .Z ( wb_clk_i_G1B2I11 ) ) ;
CLKBUF_X2 CLKBUF_X1_G1B1I1 (.A ( wb_clk_i_G1B1I1 ) , .Z ( wb_clk_i_G1B2I1 ) ) ;
CLKBUF_X2 CLKBUF_X1_G1B1I3 (.A ( wb_clk_i_G1B1I1 ) , .Z ( wb_clk_i_G1B2I3 ) ) ;
CLKBUF_X2 CLKBUF_X1_G1B1I21 (.A ( wb_clk_i_G1B1I1 ) , .Z ( wb_clk_i_G1B2I21 ) ) ;
CLKBUF_X2 CLKBUF_X1_G1B1I18 (.A ( wb_clk_i_G1B1I3 ) , .Z ( wb_clk_i_G1B2I18 ) ) ;
CLKBUF_X2 CLKBUF_X1_G1B1I15_1 (.A ( wb_clk_i_G1B1I3 ) 
    , .Z ( wb_clk_i_G1B2I15 ) ) ;
CLKBUF_X2 CLKBUF_X1_G1B1I7 (.A ( wb_clk_i_G1B1I3 ) , .Z ( wb_clk_i_G1B2I7 ) ) ;
CLKBUF_X1 CLKBUF_X1_G1B1I10 (.A ( wb_clk_i ) , .Z ( wb_clk_i_G1B2I10 ) ) ;
CLKBUF_X1 CLKBUF_X1_G1B1I9 (.A ( wb_clk_i ) , .Z ( wb_clk_i_G1B2I9 ) ) ;
OAI221_X1 U188 (.A ( n49 ) , .B1 ( n6 ) , .B2 ( n158 ) , .C1 ( n72 ) 
    , .C2 ( n37 ) , .ZN ( n117 ) ) ;
OAI221_X1 U189 (.A ( n49 ) , .B1 ( n6 ) , .B2 ( n157 ) , .C1 ( n72 ) 
    , .C2 ( n36 ) , .ZN ( n118 ) ) ;
OAI221_X1 U190 (.A ( n49 ) , .B1 ( n6 ) , .B2 ( n156 ) , .C1 ( n72 ) 
    , .C2 ( n35 ) , .ZN ( n119 ) ) ;
OAI221_X1 U191 (.A ( n49 ) , .B1 ( n6 ) , .B2 ( n155 ) , .C1 ( n72 ) 
    , .C2 ( n34 ) , .ZN ( n120 ) ) ;
OAI221_X1 U192 (.A ( n49 ) , .B1 ( n6 ) , .B2 ( n154 ) , .C1 ( n72 ) 
    , .C2 ( n33 ) , .ZN ( n121 ) ) ;
OAI221_X1 U193 (.A ( n49 ) , .B1 ( n6 ) , .B2 ( n153 ) , .C1 ( n72 ) 
    , .C2 ( n32 ) , .ZN ( n122 ) ) ;
OAI211_X1 U194 (.A ( n98 ) , .B ( n99 ) , .C1 ( n73 ) , .C2 ( n37 ) , .ZN ( N43 ) ) ;
AOI22_X1 U195 (.A1 ( ctr[2] ) , .A2 ( n82 ) , .B1 ( prer[10] ) , .B2 ( n76 ) 
    , .ZN ( n98 ) ) ;
AOI222_X1 U196 (.A1 ( rxr[2] ) , .A2 ( n79 ) , .B1 ( n150 ) , .B2 ( cr[2] ) 
    , .C1 ( n149 ) , .C2 ( txr[2] ) , .ZN ( n99 ) ) ;
OAI211_X1 U197 (.A ( n96 ) , .B ( n97 ) , .C1 ( n73 ) , .C2 ( n36 ) 
    , .ZN ( N440 ) ) ;
AOI22_X1 U198 (.A1 ( ctr[3] ) , .A2 ( n82 ) , .B1 ( prer[11] ) , .B2 ( n76 ) 
    , .ZN ( n96 ) ) ;
AOI222_X1 U199 (.A1 ( rxr[3] ) , .A2 ( n79 ) , .B1 ( n150 ) , .B2 ( cr[3] ) 
    , .C1 ( n149 ) , .C2 ( txr[3] ) , .ZN ( n97 ) ) ;
OAI211_X1 U200 (.A ( n94 ) , .B ( n95 ) , .C1 ( n73 ) , .C2 ( n35 ) , .ZN ( N45 ) ) ;
AOI22_X1 U201 (.A1 ( ctr[4] ) , .A2 ( n82 ) , .B1 ( prer[12] ) , .B2 ( n76 ) 
    , .ZN ( n94 ) ) ;
AOI222_X1 U202 (.A1 ( rxr[4] ) , .A2 ( n79 ) , .B1 ( n150 ) , .B2 ( cr[4] ) 
    , .C1 ( n149 ) , .C2 ( txr[4] ) , .ZN ( n95 ) ) ;
NOR2_X1 U203 (.A1 ( done ) , .A2 ( i2c_al ) , .ZN ( n69 ) ) ;
NOR2_X1 U204 (.A1 ( wb_rst_i ) , .A2 ( n106 ) , .ZN ( N108 ) ) ;
AOI21_X1 U205 (.A ( i2c_al ) , .B1 ( sr[5] ) , .B2 ( n40 ) , .ZN ( n106 ) ) ;
INV_X1 U206 (.A ( n78 ) , .ZN ( n2 ) ) ;
AOI21_X1 U207 (.A ( wb_rst_i ) , .B1 ( n5 ) , .B2 ( n79 ) , .ZN ( n78 ) ) ;
OAI22_X1 U208 (.A1 ( n2 ) , .A2 ( n23 ) , .B1 ( n160 ) , .B2 ( n77 ) 
    , .ZN ( n131 ) ) ;
OAI22_X1 U209 (.A1 ( n2 ) , .A2 ( n22 ) , .B1 ( n159 ) , .B2 ( n77 ) 
    , .ZN ( n132 ) ) ;
OAI22_X1 U210 (.A1 ( n2 ) , .A2 ( n21 ) , .B1 ( n158 ) , .B2 ( n77 ) 
    , .ZN ( n133 ) ) ;
OAI22_X1 U211 (.A1 ( n2 ) , .A2 ( n20 ) , .B1 ( n157 ) , .B2 ( n77 ) 
    , .ZN ( n134 ) ) ;
OAI22_X1 U212 (.A1 ( n2 ) , .A2 ( n19 ) , .B1 ( n156 ) , .B2 ( n77 ) 
    , .ZN ( n135 ) ) ;
OAI22_X1 U213 (.A1 ( n2 ) , .A2 ( n18 ) , .B1 ( n155 ) , .B2 ( n77 ) 
    , .ZN ( n136 ) ) ;
OAI22_X1 U214 (.A1 ( n2 ) , .A2 ( n17 ) , .B1 ( n154 ) , .B2 ( n77 ) 
    , .ZN ( n137 ) ) ;
OAI22_X1 U215 (.A1 ( n2 ) , .A2 ( n16 ) , .B1 ( n153 ) , .B2 ( n77 ) 
    , .ZN ( n138 ) ) ;
OAI22_X1 U216 (.A1 ( n1 ) , .A2 ( n15 ) , .B1 ( n160 ) , .B2 ( n80 ) 
    , .ZN ( n139 ) ) ;
OAI22_X1 U217 (.A1 ( n1 ) , .A2 ( n14 ) , .B1 ( n159 ) , .B2 ( n80 ) 
    , .ZN ( n140 ) ) ;
OAI22_X1 U218 (.A1 ( n1 ) , .A2 ( n13 ) , .B1 ( n158 ) , .B2 ( n80 ) 
    , .ZN ( n141 ) ) ;
OAI22_X1 U219 (.A1 ( n1 ) , .A2 ( n12 ) , .B1 ( n157 ) , .B2 ( n80 ) 
    , .ZN ( n142 ) ) ;
OAI22_X1 U220 (.A1 ( n1 ) , .A2 ( n11 ) , .B1 ( n156 ) , .B2 ( n80 ) 
    , .ZN ( n143 ) ) ;
OAI22_X1 U221 (.A1 ( n1 ) , .A2 ( n10 ) , .B1 ( n155 ) , .B2 ( n80 ) 
    , .ZN ( n144 ) ) ;
OAI22_X1 U222 (.A1 ( n1 ) , .A2 ( n9 ) , .B1 ( n154 ) , .B2 ( n80 ) 
    , .ZN ( n145 ) ) ;
OAI22_X1 U223 (.A1 ( n8 ) , .A2 ( n1 ) , .B1 ( n153 ) , .B2 ( n80 ) 
    , .ZN ( n146 ) ) ;
INV_X1 U224 (.A ( wb_adr_i[2] ) , .ZN ( n148 ) ) ;
OAI22_X1 U225 (.A1 ( n66 ) , .A2 ( n430 ) , .B1 ( n67 ) , .B2 ( n156 ) 
    , .ZN ( n113 ) ) ;
OAI22_X1 U226 (.A1 ( n66 ) , .A2 ( n420 ) , .B1 ( n67 ) , .B2 ( n155 ) 
    , .ZN ( n112 ) ) ;
OAI22_X1 U227 (.A1 ( n66 ) , .A2 ( n410 ) , .B1 ( n67 ) , .B2 ( n154 ) 
    , .ZN ( n1110 ) ) ;
OAI22_X1 U228 (.A1 ( n66 ) , .A2 ( n40 ) , .B1 ( n67 ) , .B2 ( n153 ) 
    , .ZN ( n1100 ) ) ;
OAI22_X1 U229 (.A1 ( n63 ) , .A2 ( n470 ) , .B1 ( n64 ) , .B2 ( n160 ) 
    , .ZN ( n107 ) ) ;
OAI22_X1 U230 (.A1 ( n63 ) , .A2 ( n460 ) , .B1 ( n64 ) , .B2 ( n159 ) 
    , .ZN ( n1080 ) ) ;
OAI22_X1 U231 (.A1 ( n63 ) , .A2 ( n450 ) , .B1 ( n64 ) , .B2 ( n158 ) 
    , .ZN ( n1090 ) ) ;
OR3_X1 U232 (.A1 ( n4 ) , .A2 ( wb_rst_i ) , .A3 ( n68 ) , .ZN ( n66 ) ) ;
AOI21_X1 U233 (.A ( n69 ) , .B1 ( wb_ack_o ) , .B2 ( wb_we_i ) , .ZN ( n68 ) ) ;
AND3_X1 U234 (.A1 ( wb_cyc_i ) , .A2 ( n7 ) , .A3 ( wb_stb_i ) , .ZN ( N180 ) ) ;
NOR3_X1 U235 (.A1 ( n169 ) , .A2 ( wb_rst_i ) , .A3 ( n168 ) , .ZN ( N1150 ) ) ;
AOI21_X1 U236 (.A ( wb_rst_i ) , .B1 ( n420 ) , .B2 ( n430 ) , .ZN ( N110 ) ) ;
AND2_X1 U237 (.A1 ( irxack ) , .A2 ( n49 ) , .ZN ( N109 ) ) ;
DFF_X1 wb_dat_o_reg_7_ (.D ( N48 ) , .CK ( wb_clk_i_G1B2I9 ) 
    , .Q ( wb_dat_o[7] ) ) ;
DFF_X1 wb_dat_o_reg_1_ (.D ( N42 ) , .CK ( wb_clk_i_G1B2I10 ) 
    , .Q ( wb_dat_o[1] ) ) ;
DFFR_X1 irq_flag_reg (.D ( N111 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I17 ) 
    , .Q ( sr_0 ) , .QN ( n480 ) ) ;
DFF_X1 wb_dat_o_reg_0_ (.D ( N41 ) , .CK ( wb_clk_i_G1B2I10 ) 
    , .Q ( wb_dat_o[0] ) ) ;
OAI33_X1 U120 (.A1 ( n44 ) , .A2 ( wb_rst_i ) , .A3 ( n4 ) , .B1 ( n70 ) 
    , .B2 ( n8 ) , .B3 ( n157 ) , .ZN ( n114 ) ) ;
DFFS_X1 prer_reg_15_ (.D ( n130 ) , .SN ( arst_i ) , .CK ( wb_clk_i_G1B2I15 ) 
    , .Q ( prer[15] ) , .QN ( n24 ) ) ;
DFFS_X1 prer_reg_14_ (.D ( n129 ) , .SN ( arst_i ) , .CK ( wb_clk_i_G1B2I7 ) 
    , .Q ( prer[14] ) , .QN ( n25 ) ) ;
DFFS_X1 prer_reg_13_ (.D ( n128 ) , .SN ( arst_i ) , .CK ( wb_clk_i_G1B2I7 ) 
    , .Q ( prer[13] ) , .QN ( n26 ) ) ;
DFFS_X1 prer_reg_12_ (.D ( n127 ) , .SN ( arst_i ) , .CK ( wb_clk_i_G1B2I18 ) 
    , .Q ( prer[12] ) , .QN ( n27 ) ) ;
DFFS_X1 prer_reg_11_ (.D ( n126 ) , .SN ( arst_i ) , .CK ( wb_clk_i_G1B2I18 ) 
    , .Q ( prer[11] ) , .QN ( n28 ) ) ;
DFFS_X1 prer_reg_10_ (.D ( n125 ) , .SN ( arst_i ) , .CK ( wb_clk_i_G1B2I18 ) 
    , .Q ( prer[10] ) , .QN ( n29 ) ) ;
DFFS_X1 prer_reg_9_ (.D ( n124 ) , .SN ( arst_i ) , .CK ( wb_clk_i_G1B2I18 ) 
    , .Q ( prer[9] ) , .QN ( n30 ) ) ;
DFFS_X1 prer_reg_8_ (.D ( n123 ) , .SN ( arst_i ) , .CK ( wb_clk_i_G1B2I7 ) 
    , .Q ( prer[8] ) , .QN ( n31 ) ) ;
DFFS_X1 prer_reg_7_ (.D ( n122 ) , .SN ( arst_i ) , .CK ( wb_clk_i_G1B2I15 ) 
    , .Q ( prer[7] ) , .QN ( n32 ) ) ;
DFFS_X1 prer_reg_6_ (.D ( n121 ) , .SN ( arst_i ) , .CK ( wb_clk_i_G1B2I21 ) 
    , .Q ( prer[6] ) , .QN ( n33 ) ) ;
DFFS_X1 prer_reg_5_ (.D ( n120 ) , .SN ( arst_i ) , .CK ( wb_clk_i_G1B2I21 ) 
    , .Q ( prer[5] ) , .QN ( n34 ) ) ;
DFFS_X1 prer_reg_4_ (.D ( n119 ) , .SN ( arst_i ) , .CK ( wb_clk_i_G1B2I3 ) 
    , .Q ( prer[4] ) , .QN ( n35 ) ) ;
DFFS_X1 prer_reg_3_ (.D ( n118 ) , .SN ( arst_i ) , .CK ( wb_clk_i_G1B2I15 ) 
    , .Q ( prer[3] ) , .QN ( n36 ) ) ;
DFFS_X1 prer_reg_2_ (.D ( n117 ) , .SN ( arst_i ) , .CK ( wb_clk_i_G1B2I3 ) 
    , .Q ( prer[2] ) , .QN ( n37 ) ) ;
DFFS_X1 prer_reg_1_ (.D ( n116 ) , .SN ( arst_i ) , .CK ( wb_clk_i_G1B2I15 ) 
    , .Q ( prer[1] ) , .QN ( n38 ) ) ;
DFFS_X1 prer_reg_0_ (.D ( n115 ) , .SN ( arst_i ) , .CK ( wb_clk_i_G1B2I15 ) 
    , .Q ( prer[0] ) , .QN ( n39 ) ) ;
DFFR_X1 tip_reg (.D ( N110 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I19 ) 
    , .Q ( sr_1 ) ) ;
DFFR_X1 rxack_reg (.D ( N109 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I1 ) 
    , .Q ( sr[7] ) ) ;
DFFR_X1 wb_inta_o_reg (.D ( N1150 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I18 ) 
    , .Q ( wb_inta_o ) ) ;
DFFR_X1 al_reg (.D ( N108 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I19 ) 
    , .Q ( sr[5] ) ) ;
DFFR_X1 cr_reg_1_ (.D ( n1080 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I14 ) 
    , .QN ( n460 ) ) ;
INV_X1 U121 (.A ( wb_rst_i ) , .ZN ( n49 ) ) ;
INV_X1 U122 (.A ( n72 ) , .ZN ( n6 ) ) ;
INV_X1 U123 (.A ( n75 ) , .ZN ( n3 ) ) ;
NAND2_X1 U124 (.A1 ( n5 ) , .A2 ( n63 ) , .ZN ( n64 ) ) ;
NOR2_X1 U125 (.A1 ( n73 ) , .A2 ( n74 ) , .ZN ( n72 ) ) ;
NAND3_X1 U126 (.A1 ( n151 ) , .A2 ( n148 ) , .A3 ( n152 ) , .ZN ( n73 ) ) ;
NAND2_X1 U127 (.A1 ( n76 ) , .A2 ( n5 ) , .ZN ( n75 ) ) ;
INV_X1 U128 (.A ( n74 ) , .ZN ( n5 ) ) ;
NAND2_X1 U129 (.A1 ( n5 ) , .A2 ( n2 ) , .ZN ( n77 ) ) ;
NAND2_X1 U130 (.A1 ( n5 ) , .A2 ( n1 ) , .ZN ( n80 ) ) ;
NAND2_X1 U131 (.A1 ( n5 ) , .A2 ( n65 ) , .ZN ( n63 ) ) ;
NAND2_X1 U132 (.A1 ( n5 ) , .A2 ( n66 ) , .ZN ( n67 ) ) ;
INV_X1 U133 (.A ( n86 ) , .ZN ( n149 ) ) ;
INV_X1 U134 (.A ( n87 ) , .ZN ( n150 ) ) ;
INV_X1 U135 (.A ( n65 ) , .ZN ( n4 ) ) ;
NOR3_X1 U136 (.A1 ( wb_adr_i[0] ) , .A2 ( wb_adr_i[1] ) , .A3 ( n148 ) 
    , .ZN ( n71 ) ) ;
NOR3_X2 U137 (.A1 ( wb_adr_i[1] ) , .A2 ( wb_adr_i[2] ) , .A3 ( n152 ) 
    , .ZN ( n76 ) ) ;
NOR3_X1 U138 (.A1 ( wb_adr_i[0] ) , .A2 ( wb_adr_i[2] ) , .A3 ( n151 ) 
    , .ZN ( n82 ) ) ;
NOR3_X2 U139 (.A1 ( n152 ) , .A2 ( wb_adr_i[2] ) , .A3 ( n151 ) , .ZN ( n79 ) ) ;
NAND3_X1 U140 (.A1 ( wb_adr_i[2] ) , .A2 ( n151 ) , .A3 ( wb_adr_i[0] ) 
    , .ZN ( n86 ) ) ;
NAND3_X1 U141 (.A1 ( wb_adr_i[2] ) , .A2 ( n152 ) , .A3 ( wb_adr_i[1] ) 
    , .ZN ( n87 ) ) ;
NAND3_X1 U142 (.A1 ( wb_ack_o ) , .A2 ( n49 ) , .A3 ( wb_we_i ) , .ZN ( n74 ) ) ;
NAND2_X1 U143 (.A1 ( n5 ) , .A2 ( n71 ) , .ZN ( n70 ) ) ;
INV_X1 U144 (.A ( n81 ) , .ZN ( n1 ) ) ;
AOI21_X1 U145 (.A ( wb_rst_i ) , .B1 ( n5 ) , .B2 ( n82 ) , .ZN ( n81 ) ) ;
INV_X1 U146 (.A ( wb_adr_i[0] ) , .ZN ( n152 ) ) ;
NAND3_X1 U147 (.A1 ( n5 ) , .A2 ( n71 ) , .A3 ( ctr[7] ) , .ZN ( n65 ) ) ;
INV_X1 U148 (.A ( wb_adr_i[1] ) , .ZN ( n151 ) ) ;
AOI211_X1 U149 (.A ( wb_rst_i ) , .B ( cr[0] ) , .C1 ( n69 ) , .C2 ( n480 ) 
    , .ZN ( N111 ) ) ;
INV_X1 U150 (.A ( wb_dat_i[0] ) , .ZN ( n160 ) ) ;
INV_X1 U151 (.A ( wb_dat_i[1] ) , .ZN ( n159 ) ) ;
INV_X1 U152 (.A ( wb_dat_i[2] ) , .ZN ( n158 ) ) ;
INV_X1 U153 (.A ( wb_dat_i[4] ) , .ZN ( n156 ) ) ;
INV_X1 U154 (.A ( wb_dat_i[5] ) , .ZN ( n155 ) ) ;
INV_X1 U155 (.A ( wb_dat_i[6] ) , .ZN ( n154 ) ) ;
INV_X1 U156 (.A ( wb_dat_i[7] ) , .ZN ( n153 ) ) ;
OAI221_X1 U157 (.A ( n49 ) , .B1 ( n75 ) , .B2 ( n160 ) , .C1 ( n3 ) 
    , .C2 ( n31 ) , .ZN ( n123 ) ) ;
OAI221_X1 U158 (.A ( n49 ) , .B1 ( n75 ) , .B2 ( n159 ) , .C1 ( n3 ) 
    , .C2 ( n30 ) , .ZN ( n124 ) ) ;
OAI221_X1 U159 (.A ( n49 ) , .B1 ( n75 ) , .B2 ( n158 ) , .C1 ( n3 ) 
    , .C2 ( n29 ) , .ZN ( n125 ) ) ;
OAI221_X1 U160 (.A ( n49 ) , .B1 ( n75 ) , .B2 ( n157 ) , .C1 ( n3 ) 
    , .C2 ( n28 ) , .ZN ( n126 ) ) ;
OAI221_X1 U161 (.A ( n49 ) , .B1 ( n75 ) , .B2 ( n156 ) , .C1 ( n3 ) 
    , .C2 ( n27 ) , .ZN ( n127 ) ) ;
OAI221_X1 U162 (.A ( n49 ) , .B1 ( n75 ) , .B2 ( n155 ) , .C1 ( n3 ) 
    , .C2 ( n26 ) , .ZN ( n128 ) ) ;
OAI221_X1 U163 (.A ( n49 ) , .B1 ( n75 ) , .B2 ( n154 ) , .C1 ( n3 ) 
    , .C2 ( n25 ) , .ZN ( n129 ) ) ;
OAI221_X1 U164 (.A ( n49 ) , .B1 ( n75 ) , .B2 ( n153 ) , .C1 ( n3 ) 
    , .C2 ( n24 ) , .ZN ( n130 ) ) ;
INV_X1 U165 (.A ( wb_dat_i[3] ) , .ZN ( n157 ) ) ;
OAI211_X1 U166 (.A ( n103 ) , .B ( n104 ) , .C1 ( n73 ) , .C2 ( n39 ) 
    , .ZN ( N41 ) ) ;
AOI22_X1 U167 (.A1 ( ctr[0] ) , .A2 ( n82 ) , .B1 ( prer[8] ) , .B2 ( n76 ) 
    , .ZN ( n103 ) ) ;
AOI221_X1 U168 (.A ( n105 ) , .B1 ( sr_0 ) , .B2 ( n71 ) , .C1 ( rxr[0] ) 
    , .C2 ( n79 ) , .ZN ( n104 ) ) ;
OAI22_X1 U169 (.A1 ( n23 ) , .A2 ( n86 ) , .B1 ( n470 ) , .B2 ( n87 ) 
    , .ZN ( n105 ) ) ;
OAI211_X1 U170 (.A ( n100 ) , .B ( n101 ) , .C1 ( n73 ) , .C2 ( n38 ) 
    , .ZN ( N42 ) ) ;
AOI22_X1 U171 (.A1 ( ctr[1] ) , .A2 ( n82 ) , .B1 ( prer[9] ) , .B2 ( n76 ) 
    , .ZN ( n100 ) ) ;
AOI221_X1 U172 (.A ( n102 ) , .B1 ( sr_1 ) , .B2 ( n71 ) , .C1 ( rxr[1] ) 
    , .C2 ( n79 ) , .ZN ( n101 ) ) ;
OAI22_X1 U173 (.A1 ( n22 ) , .A2 ( n86 ) , .B1 ( n460 ) , .B2 ( n87 ) 
    , .ZN ( n102 ) ) ;
OAI211_X1 U174 (.A ( n83 ) , .B ( n84 ) , .C1 ( n73 ) , .C2 ( n32 ) , .ZN ( N48 ) ) ;
AOI22_X1 U175 (.A1 ( n82 ) , .A2 ( ctr[7] ) , .B1 ( prer[15] ) , .B2 ( n76 ) 
    , .ZN ( n83 ) ) ;
AOI221_X1 U176 (.A ( n85 ) , .B1 ( sr[7] ) , .B2 ( n71 ) , .C1 ( rxr[7] ) 
    , .C2 ( n79 ) , .ZN ( n84 ) ) ;
OAI22_X1 U177 (.A1 ( n16 ) , .A2 ( n86 ) , .B1 ( n40 ) , .B2 ( n87 ) 
    , .ZN ( n85 ) ) ;
OAI211_X1 U178 (.A ( n91 ) , .B ( n92 ) , .C1 ( n73 ) , .C2 ( n34 ) , .ZN ( N46 ) ) ;
AOI22_X1 U179 (.A1 ( ctr[5] ) , .A2 ( n82 ) , .B1 ( prer[13] ) , .B2 ( n76 ) 
    , .ZN ( n91 ) ) ;
AOI221_X1 U180 (.A ( n93 ) , .B1 ( sr[5] ) , .B2 ( n71 ) , .C1 ( rxr[5] ) 
    , .C2 ( n79 ) , .ZN ( n92 ) ) ;
OAI22_X1 U181 (.A1 ( n18 ) , .A2 ( n86 ) , .B1 ( n420 ) , .B2 ( n87 ) 
    , .ZN ( n93 ) ) ;
OAI211_X1 U182 (.A ( n88 ) , .B ( n89 ) , .C1 ( n73 ) , .C2 ( n33 ) , .ZN ( N47 ) ) ;
AOI22_X1 U183 (.A1 ( ctr[6] ) , .A2 ( n82 ) , .B1 ( prer[14] ) , .B2 ( n76 ) 
    , .ZN ( n88 ) ) ;
AOI221_X1 U184 (.A ( n90 ) , .B1 ( sr[6] ) , .B2 ( n71 ) , .C1 ( rxr[6] ) 
    , .C2 ( n79 ) , .ZN ( n89 ) ) ;
OAI22_X1 U185 (.A1 ( n17 ) , .A2 ( n86 ) , .B1 ( n410 ) , .B2 ( n87 ) 
    , .ZN ( n90 ) ) ;
OAI221_X1 U186 (.A ( n49 ) , .B1 ( n6 ) , .B2 ( n160 ) , .C1 ( n72 ) 
    , .C2 ( n39 ) , .ZN ( n115 ) ) ;
OAI221_X1 U187 (.A ( n49 ) , .B1 ( n6 ) , .B2 ( n159 ) , .C1 ( n72 ) 
    , .C2 ( n38 ) , .ZN ( n116 ) ) ;
DFF_X1 wb_ack_o_reg (.D ( N180 ) , .CK ( wb_clk_i_G1B2I8 ) , .Q ( wb_ack_o ) 
    , .QN ( n7 ) ) ;
DFFR_X1 ctr_reg_7_ (.D ( n146 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I19 ) 
    , .Q ( ctr[7] ) , .QN ( n8 ) ) ;
DFFR_X1 ctr_reg_6_ (.D ( n145 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I19 ) 
    , .Q ( ctr[6] ) , .QN ( n9 ) ) ;
DFFR_X1 ctr_reg_5_ (.D ( n144 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I6 ) 
    , .Q ( ctr[5] ) , .QN ( n10 ) ) ;
DFFR_X1 ctr_reg_4_ (.D ( n143 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I6 ) 
    , .Q ( ctr[4] ) , .QN ( n11 ) ) ;
DFFR_X1 ctr_reg_3_ (.D ( n142 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I18 ) 
    , .Q ( ctr[3] ) , .QN ( n12 ) ) ;
DFFR_X1 ctr_reg_2_ (.D ( n141 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I6 ) 
    , .Q ( ctr[2] ) , .QN ( n13 ) ) ;
DFFR_X1 ctr_reg_1_ (.D ( n140 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I6 ) 
    , .Q ( ctr[1] ) , .QN ( n14 ) ) ;
DFFR_X1 ctr_reg_0_ (.D ( n139 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I18 ) 
    , .Q ( ctr[0] ) , .QN ( n15 ) ) ;
DFFR_X1 txr_reg_7_ (.D ( n138 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I5 ) 
    , .Q ( txr[7] ) , .QN ( n16 ) ) ;
DFFR_X1 txr_reg_6_ (.D ( n137 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I5 ) 
    , .Q ( txr[6] ) , .QN ( n17 ) ) ;
DFFR_X1 txr_reg_5_ (.D ( n136 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I14 ) 
    , .Q ( txr[5] ) , .QN ( n18 ) ) ;
DFFR_X1 txr_reg_4_ (.D ( n135 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I17 ) 
    , .Q ( txr[4] ) , .QN ( n19 ) ) ;
DFFR_X1 txr_reg_3_ (.D ( n134 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I17 ) 
    , .Q ( txr[3] ) , .QN ( n20 ) ) ;
DFFR_X1 txr_reg_2_ (.D ( n133 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I17 ) 
    , .Q ( txr[2] ) , .QN ( n21 ) ) ;
DFFR_X1 txr_reg_1_ (.D ( n132 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I14 ) 
    , .Q ( txr[1] ) , .QN ( n22 ) ) ;
DFFR_X1 txr_reg_0_ (.D ( n131 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I14 ) 
    , .Q ( txr[0] ) , .QN ( n23 ) ) ;
DFFR_X1 cr_reg_3_ (.D ( n114 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I19 ) 
    , .Q ( cr[3] ) , .QN ( n44 ) ) ;
DFFR_X1 cr_reg_7_ (.D ( n1100 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I12 ) 
    , .Q ( cr[7] ) , .QN ( n40 ) ) ;
DFFR_X1 cr_reg_6_ (.D ( n1110 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I19 ) 
    , .Q ( cr[6] ) , .QN ( n410 ) ) ;
DFF_X1 wb_dat_o_reg_6_ (.D ( N47 ) , .CK ( wb_clk_i_G1B2I9 ) 
    , .Q ( wb_dat_o[6] ) ) ;
DFFR_X1 cr_reg_5_ (.D ( n112 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I19 ) 
    , .Q ( cr[5] ) , .QN ( n420 ) ) ;
DFFR_X1 cr_reg_4_ (.D ( n113 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I19 ) 
    , .Q ( cr[4] ) , .QN ( n430 ) ) ;
DFF_X1 wb_dat_o_reg_4_ (.D ( N45 ) , .CK ( wb_clk_i_G1B2I20 ) 
    , .Q ( wb_dat_o[4] ) ) ;
DFF_X1 wb_dat_o_reg_3_ (.D ( N440 ) , .CK ( wb_clk_i_G1B2I20 ) 
    , .Q ( wb_dat_o[3] ) ) ;
DFFR_X1 cr_reg_2_ (.D ( n1090 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I6 ) 
    , .Q ( cr[2] ) , .QN ( n450 ) ) ;
DFF_X1 wb_dat_o_reg_2_ (.D ( N43 ) , .CK ( wb_clk_i_G1B2I20 ) 
    , .Q ( wb_dat_o[2] ) ) ;
DFFR_X1 cr_reg_0_ (.D ( n107 ) , .RN ( arst_i ) , .CK ( wb_clk_i_G1B2I6 ) 
    , .Q ( cr[0] ) , .QN ( n470 ) ) ;
DFF_X1 wb_dat_o_reg_5_ (.D ( N46 ) , .CK ( wb_clk_i_G1B2I11 ) 
    , .Q ( wb_dat_o[5] ) ) ;
NOR2_X4 SPARE_PREFIX_NAME_0 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NOR2_X4 SPARE_PREFIX_NAME_1 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NOR2_X4 SPARE_PREFIX_NAME_2 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NOR2_X4 SPARE_PREFIX_NAME_3 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NOR2_X4 SPARE_PREFIX_NAME_4 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NOR2_X4 SPARE_PREFIX_NAME_5 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NOR2_X4 SPARE_PREFIX_NAME_6 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NOR2_X4 SPARE_PREFIX_NAME_7 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NOR2_X4 SPARE_PREFIX_NAME_8 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NOR2_X4 SPARE_PREFIX_NAME_9 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NOR2_X4 SPARE_PREFIX_NAME_10 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NOR2_X4 SPARE_PREFIX_NAME_11 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NOR2_X4 SPARE_PREFIX_NAME_12 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NOR2_X4 SPARE_PREFIX_NAME_13 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NOR2_X4 SPARE_PREFIX_NAME_14 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NOR2_X4 SPARE_PREFIX_NAME_15 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NOR2_X4 SPARE_PREFIX_NAME_16 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NOR2_X4 SPARE_PREFIX_NAME_17 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NOR2_X4 SPARE_PREFIX_NAME_18 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NOR2_X4 SPARE_PREFIX_NAME_19 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NAND2_X4 SPARE_PREFIX_NAME_0_0 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NAND2_X4 SPARE_PREFIX_NAME_0_1 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NAND2_X4 SPARE_PREFIX_NAME_0_2 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NAND2_X4 SPARE_PREFIX_NAME_0_3 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NAND2_X4 SPARE_PREFIX_NAME_0_4 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NAND2_X4 SPARE_PREFIX_NAME_0_5 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NAND2_X4 SPARE_PREFIX_NAME_0_6 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NAND2_X4 SPARE_PREFIX_NAME_0_7 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NAND2_X4 SPARE_PREFIX_NAME_0_8 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NAND2_X4 SPARE_PREFIX_NAME_0_9 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NAND2_X4 SPARE_PREFIX_NAME_0_10 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NAND2_X4 SPARE_PREFIX_NAME_0_11 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NAND2_X4 SPARE_PREFIX_NAME_0_12 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NAND2_X4 SPARE_PREFIX_NAME_0_13 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NAND2_X4 SPARE_PREFIX_NAME_0_14 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NAND2_X4 SPARE_PREFIX_NAME_0_15 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NAND2_X4 SPARE_PREFIX_NAME_0_16 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NAND2_X4 SPARE_PREFIX_NAME_0_17 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NAND2_X4 SPARE_PREFIX_NAME_0_18 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
NAND2_X4 SPARE_PREFIX_NAME_0_19 (.A1 ( 1'b0 )
    , .A2 ( 1'b0 )) ;
assign sda_pad_o = 1'b0;
endmodule


