set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction horizontal  -start_at 1.3000 -nets VDD -layer 19 -width 1.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 50.9000 -nets VDD -layer 19 -width 1.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 52.2000 -nets VDD -layer 21 -width 1.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1.3000 -nets VDD -layer 21 -width 1.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1.3000 -nets VDD -layer 23 -width 1.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 50.9000 -nets VDD -layer 23 -width 1.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 52.2000 -nets VDD -layer 25 -width 1.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1.3000 -nets VDD -layer 25 -width 1.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 3.1000 -nets VSS -layer 19 -width 1.0000 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 49.1000 -nets VSS -layer 19 -width 1.0000 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 50.4000 -nets VSS -layer 21 -width 1.0000 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 3.1000 -nets VSS -layer 21 -width 1.0000 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 3.1000 -nets VSS -layer 23 -width 1.0000 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 49.1000 -nets VSS -layer 23 -width 1.0000 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 50.4000 -nets VSS -layer 25 -width 1.0000 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 3.1000 -nets VSS -layer 25 -width 1.0000 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal4 straps for net VDD
create_power_straps  -direction vertical  -start_at 6.2900 -nets VDD  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 9.7100 -nets VDD  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 13.1300 -nets VDD  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 16.5500 -nets VDD  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 19.5900 -nets VDD  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 23.0100 -nets VDD  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 26.4300 -nets VDD  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 29.8500 -nets VDD  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 33.2700 -nets VDD  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 36.3100 -nets VDD  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 39.7300 -nets VDD  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 43.1500 -nets VDD  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 46.5700 -nets VDD  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal4 straps for net VSS
create_power_straps  -direction vertical  -start_at 6.9300 -nets VSS  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 10.3500 -nets VSS  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 13.7700 -nets VSS  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 17.1900 -nets VSS  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 20.2300 -nets VSS  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 23.6500 -nets VSS  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 27.0700 -nets VSS  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 30.4900 -nets VSS  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 33.9100 -nets VSS  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 36.9500 -nets VSS  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 40.3700 -nets VSS  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 43.7900 -nets VSS  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 47.2100 -nets VSS  -layer 17 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal5 straps for net VDD
create_power_straps  -direction horizontal  -start_at 6.4800 -nets VDD  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 9.5200 -nets VDD  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 12.5600 -nets VDD  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 16.3600 -nets VDD  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 19.4000 -nets VDD  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 22.4400 -nets VDD  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 25.4800 -nets VDD  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 29.2800 -nets VDD  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 32.3200 -nets VDD  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 35.3600 -nets VDD  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 39.1600 -nets VDD  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 42.2000 -nets VDD  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 45.2400 -nets VDD  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal5 straps for net VSS
create_power_straps  -direction horizontal  -start_at 7.1200 -nets VSS  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 10.1600 -nets VSS  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 13.2000 -nets VSS  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 17.0000 -nets VSS  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 20.0400 -nets VSS  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 23.0800 -nets VSS  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 26.1200 -nets VSS  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 29.9200 -nets VSS  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 32.9600 -nets VSS  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 36.0000 -nets VSS  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 39.8000 -nets VSS  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 42.8400 -nets VSS  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 45.8800 -nets VSS  -layer 19 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal6 straps for net VDD
create_power_straps  -direction vertical  -start_at 6.0350 -nets VDD  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 9.8350 -nets VDD  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 12.8750 -nets VDD  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 16.6750 -nets VDD  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 19.7150 -nets VDD  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 22.7550 -nets VDD  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 26.5550 -nets VDD  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 29.5950 -nets VDD  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 33.3950 -nets VDD  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 36.4350 -nets VDD  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 39.4750 -nets VDD  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 43.2750 -nets VDD  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 46.3150 -nets VDD  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal6 straps for net VSS
create_power_straps  -direction vertical  -start_at 6.8050 -nets VSS  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 10.6050 -nets VSS  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 13.6450 -nets VSS  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 17.4450 -nets VSS  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 20.4850 -nets VSS  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 23.5250 -nets VSS  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 27.3250 -nets VSS  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 30.3650 -nets VSS  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 34.1650 -nets VSS  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 37.2050 -nets VSS  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 40.2450 -nets VSS  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 44.0450 -nets VSS  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 47.0850 -nets VSS  -layer 21 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal7 straps for net VDD
create_power_straps  -direction horizontal  -start_at 5.5250 -nets VDD  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 8.5650 -nets VDD  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 13.1250 -nets VDD  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 16.1650 -nets VDD  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 19.2050 -nets VDD  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 22.2450 -nets VDD  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 25.2850 -nets VDD  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 28.3250 -nets VDD  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 31.3650 -nets VDD  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 35.9250 -nets VDD  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 38.9650 -nets VDD  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 42.0050 -nets VDD  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 45.0450 -nets VDD  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 52.7000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal7 straps for net VSS
create_power_straps  -direction horizontal  -start_at 6.5550 -nets VSS  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 9.5950 -nets VSS  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 14.1550 -nets VSS  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 17.1950 -nets VSS  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 20.2350 -nets VSS  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 23.2750 -nets VSS  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 26.3150 -nets VSS  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 29.3550 -nets VSS  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 32.3950 -nets VSS  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 36.9550 -nets VSS  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 39.9950 -nets VSS  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 43.0350 -nets VSS  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 46.0750 -nets VSS  -layer 23 -width 0.5000 -pitch_within_group 3.2570 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 50.9000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VDD
create_power_straps  -direction vertical  -start_at 6.3500 -nets VDD  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 9.3900 -nets VDD  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 12.4300 -nets VDD  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 16.9900 -nets VDD  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 20.0300 -nets VDD  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 23.0700 -nets VDD  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 26.1100 -nets VDD  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 29.1500 -nets VDD  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 33.7100 -nets VDD  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 36.7500 -nets VDD  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 39.7900 -nets VDD  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 42.8300 -nets VDD  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 45.8700 -nets VDD  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 51.4000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VSS
create_power_straps  -direction vertical  -start_at 7.2500 -nets VSS  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 10.2900 -nets VSS  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 13.3300 -nets VSS  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 17.8900 -nets VSS  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 20.9300 -nets VSS  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 23.9700 -nets VSS  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 27.0100 -nets VSS  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 30.0500 -nets VSS  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 34.6100 -nets VSS  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 37.6500 -nets VSS  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 40.6900 -nets VSS  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 43.7300 -nets VSS  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 46.7700 -nets VSS  -layer 25 -width 0.5000 -pitch_within_group 3.3500 -start_low_ends coordinate  -start_low_ends_coordinate 2.6000 -start_high_ends coordinate  -start_high_ends_coordinate 49.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
